// playground/react/src/components/custom/PreviewColorPicker.tsx
/**
 * ColorPicker 的阅读态组件（readPretty）
 *
 * 阅读态下显示色块 + HEX 文本，不可交互。
 * 演示 registerComponent 的 readPrettyComponent 选项。
 */

interface PreviewColorPickerProps {
  value?: string
}

export function PreviewColorPicker({ value }: PreviewColorPickerProps): JSX.Element {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
      <span style={{
        width: 16, height: 16, borderRadius: 3,
        background: value || '#000', border: '1px solid #d9d9d9',
        display: 'inline-block',
      }} />
      <span style={{ fontFamily: 'monospace', fontSize: 13 }}>{value || '—'}</span>
    </span>
  )
}

// playground/vue/src/components/custom/PreviewColorPicker.vue
<template>
  <span :style="wrapperStyle">
    <span :style="swatchStyle" />
    <span :style="textStyle">{{ displayValue }}</span>
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  modelValue?: string
}>()

const displayValue = computed(() => (props.modelValue && props.modelValue.length > 0 ? props.modelValue : '—'))
const swatchColor = computed(() => {
  const value = props.modelValue ?? ''
  return /^#[0-9a-f]{6}$/i.test(value) ? value : '#000000'
})

const wrapperStyle = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: '6px',
} as const

const swatchStyle = computed(() => ({
  width: '16px',
  height: '16px',
  borderRadius: '3px',
  background: swatchColor.value,
  border: '1px solid #d9d9d9',
  display: 'inline-block',
}))

const textStyle = {
  fontFamily: 'monospace',
  fontSize: '13px',
} as const
</script>
