// playground-react/src/antd/field/DataProcessForm.tsx
/**
 * 数据处理 - antd 版
 *
 * 覆盖场景：
 * - 值格式化（format：金额→¥1,234.56）
 * - 值解析（parse：千分位→数字）
 * - 提交前转换（transform：元→分）
 * - 路径映射（submitPath）
 * - 隐藏字段排除（excludeWhenHidden）
 * - 脏检测（form.modified）
 * - 值变化日志
 */
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import {
  Button, Typography, Alert, Input, Switch, Form, Space, Badge, Tag, List,
} from 'antd';
import type { FieldInstance } from '@moluoxixi/core';

const { Title, Paragraph, Text } = Typography;

setupAntd();

/** 值变化日志条目 */
interface ChangeLogEntry {
  time: string;
  field: string;
  value: unknown;
}

/** 将数字格式化为千分位货币显示 */
function formatCurrency(val: unknown): string {
  const num = Number(val);
  if (Number.isNaN(num) || val === '' || val === null || val === undefined) return '';
  return `¥${num.toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/** 解析千分位输入为数字 */
function parseCurrencyInput(input: unknown): number {
  if (typeof input !== 'string') return Number(input) || 0;
  const cleaned = input.replace(/[¥,\s]/g, '');
  const num = Number(cleaned);
  return Number.isNaN(num) ? 0 : num;
}

/** 元转分 */
function yuanToFen(val: unknown): number {
  return Math.round(Number(val) * 100);
}

/** 去除空字符串 */
function trimEmpty(val: unknown): unknown {
  if (typeof val === 'string' && val.trim() === '') return undefined;
  return val;
}

/** 当前时间 */
function now(): string {
  return new Date().toLocaleTimeString('zh-CN', { hour12: false });
}

/** 最大日志条数 */
const MAX_LOG_COUNT = 50;

/**
 * 数据处理示例
 */
export const DataProcessForm = observer(() => {
  const form = useCreateForm({
    initialValues: {
      productName: '示例商品',
      price: 1234.56,
      discount: 0.85,
      hasRemark: true,
      remark: '这是备注',
      internalCode: 'SKU-001',
    },
  });

  const [submitResult, setSubmitResult] = useState('');
  const [changeLog, setChangeLog] = useState<ChangeLogEntry[]>([]);
  const logEndRef = useRef<HTMLDivElement>(null);

  /** 追加日志 */
  const appendLog = useCallback((field: string, value: unknown): void => {
    setChangeLog((prev) => {
      const next = [...prev, { time: now(), field, value }];
      return next.length > MAX_LOG_COUNT ? next.slice(-MAX_LOG_COUNT) : next;
    });
  }, []);

  /* 创建字段 */
  useEffect(() => {
    form.createField({ name: 'productName', label: '商品名称', required: true, transform: trimEmpty });
    form.createField({
      name: 'price',
      label: '价格（元）',
      required: true,
      format: formatCurrency,
      parse: parseCurrencyInput,
      transform: yuanToFen,
      submitPath: 'pricing.amountInFen',
    });
    form.createField({
      name: 'discount',
      label: '折扣',
      required: true,
      format: (val: unknown): string => {
        const num = Number(val);
        if (Number.isNaN(num)) return '';
        return `${(num * 100).toFixed(0)}%`;
      },
      parse: (input: unknown): number => {
        const str = String(input).replace('%', '');
        const num = Number(str);
        if (Number.isNaN(num)) return 0;
        return num > 1 ? num / 100 : num;
      },
      submitPath: 'pricing.discount',
    });
    form.createField({ name: 'hasRemark', label: '添加备注' });
    form.createField({
      name: 'remark',
      label: '备注',
      excludeWhenHidden: true,
      transform: trimEmpty,
      reactions: [
        {
          watch: 'hasRemark',
          fulfill: {
            run: (field, ctx) => {
              if (ctx.values.hasRemark) {
                field.show();
              } else {
                field.hide();
              }
            },
          },
        },
      ],
    });
    form.createField({
      name: 'internalCode',
      label: '内部编码',
      submitPath: 'meta.internalCode',
      transform: trimEmpty,
    });

    const disposeValues = form.onValuesChange((values) => appendLog('【全量】', values));
    const disposePrice = form.onFieldValueChange('price', (value) => appendLog('price', value));

    return () => {
      disposeValues();
      disposePrice();
    };
  }, [appendLog]);

  /* 日志滚动到底部 */
  useEffect(() => {
    logEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [changeLog]);

  /** 提交 */
  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    const result = await form.submit();
    if (result.errors.length > 0) {
      setSubmitResult('验证失败: ' + result.errors.map((err) => err.message).join(', '));
    } else {
      setSubmitResult(JSON.stringify(result.values, null, 2));
    }
  };

  /** 重置 */
  const handleReset = (): void => {
    form.reset();
    setSubmitResult('');
    setChangeLog([]);
  };

  return (
    <div>
      <Title level={3}>数据处理 - antd 版</Title>
      <Paragraph type="secondary">
        format / parse / transform / submitPath / excludeWhenHidden / 脏检测 / 变化日志
      </Paragraph>

      {/* 脏检测指示器 */}
      <div style={{ marginBottom: 16 }}>
        <Badge status={form.modified ? 'warning' : 'success'} text={form.modified ? '已修改（有未保存的更改）' : '未修改'} />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
        {/* 左侧：表单 */}
        <div>
          <FormProvider form={form}>
            <form onSubmit={handleSubmit} noValidate>
              {/* 商品名称 */}
              <FormField name="productName">
                {(field: FieldInstance) => (
                  <Form.Item label={field.label} required={field.required} validateStatus={field.errors.length > 0 ? 'error' : undefined} help={field.errors[0]?.message}>
                    <Input
                      value={(field.value as string) ?? ''}
                      onChange={(e) => field.setValue(e.target.value)}
                      onBlur={() => { field.blur(); field.validate('blur').catch(() => {}); }}
                    />
                  </Form.Item>
                )}
              </FormField>

              {/* 价格（格式化/解析） */}
              <FormField name="price">
                {(field: FieldInstance) => {
                  const displayValue = field.format ? String(field.format(field.value)) : String(field.value ?? '');
                  return (
                    <Form.Item label={field.label} required={field.required} validateStatus={field.errors.length > 0 ? 'error' : undefined} help={field.errors[0]?.message}>
                      <Input
                        value={displayValue}
                        onChange={(e) => {
                          const parsed = field.parse ? field.parse(e.target.value) : e.target.value;
                          field.setValue(parsed);
                        }}
                        placeholder="输入金额"
                      />
                      <div style={{ marginTop: 4 }}>
                        <Tag>存储值: {String(field.value)}</Tag>
                        <Tag color="green">提交值(分): {field.transform ? String(field.transform(field.value)) : '-'}</Tag>
                      </div>
                    </Form.Item>
                  );
                }}
              </FormField>

              {/* 折扣 */}
              <FormField name="discount">
                {(field: FieldInstance) => {
                  const displayValue = field.format ? String(field.format(field.value)) : String(field.value ?? '');
                  return (
                    <Form.Item label={field.label} required={field.required}>
                      <Input
                        value={displayValue}
                        onChange={(e) => {
                          const parsed = field.parse ? field.parse(e.target.value) : e.target.value;
                          field.setValue(parsed);
                        }}
                        placeholder="如 0.85 或 85%"
                      />
                      <Tag style={{ marginTop: 4 }}>存储值: {String(field.value)}</Tag>
                    </Form.Item>
                  );
                }}
              </FormField>

              {/* 备注开关 */}
              <FormField name="hasRemark">
                {(field: FieldInstance) => (
                  <Form.Item label={field.label}>
                    <Switch checked={!!field.value} onChange={(checked) => field.setValue(checked)} />
                  </Form.Item>
                )}
              </FormField>

              {/* 备注 */}
              <FormField name="remark">
                {(field: FieldInstance) => {
                  if (!field.visible) return null;
                  return (
                    <Form.Item label={<>{field.label} <Tag>隐藏时不提交</Tag></>}>
                      <Input.TextArea
                        value={(field.value as string) ?? ''}
                        onChange={(e) => field.setValue(e.target.value)}
                        rows={3}
                      />
                    </Form.Item>
                  );
                }}
              </FormField>

              {/* 内部编码 */}
              <FormField name="internalCode">
                {(field: FieldInstance) => (
                  <Form.Item label={<>{field.label} <Tag>submitPath: meta.internalCode</Tag></>}>
                    <Input
                      value={(field.value as string) ?? ''}
                      onChange={(e) => field.setValue(e.target.value)}
                    />
                  </Form.Item>
                )}
              </FormField>

              <Space>
                <Button type="primary" htmlType="submit">提交</Button>
                <Button onClick={handleReset}>重置</Button>
              </Space>
            </form>
          </FormProvider>

          {submitResult && (
            <Alert
              style={{ marginTop: 16 }}
              type={submitResult.startsWith('验证失败') ? 'error' : 'success'}
              message="提交数据（transform + submitPath 映射后）"
              description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontSize: 12 }}>{submitResult}</pre>}
            />
          )}
        </div>

        {/* 右侧：值变化日志 */}
        <div>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
            <Text strong>值变化日志</Text>
            <Button size="small" onClick={() => setChangeLog([])}>清空</Button>
          </div>
          <div
            style={{
              height: 500,
              overflow: 'auto',
              border: '1px solid #eee',
              borderRadius: 6,
              padding: 8,
              background: '#fafafa',
              fontSize: 12,
              fontFamily: 'monospace',
            }}
          >
            {changeLog.length === 0 && (
              <div style={{ color: '#999', textAlign: 'center', padding: 20 }}>暂无记录</div>
            )}
            {changeLog.map((entry, i) => (
              <div key={i} style={{ marginBottom: 4, padding: '4px 8px', background: '#fff', borderRadius: 4, borderLeft: '3px solid #1677ff' }}>
                <Text type="secondary">[{entry.time}]</Text>{' '}
                <Text type="success" strong>{entry.field}</Text>:{' '}
                <span>{typeof entry.value === 'object' ? JSON.stringify(entry.value) : String(entry.value)}</span>
              </div>
            ))}
            <div ref={logEndRef} />
          </div>
        </div>
      </div>
    </div>
  );
});

// playground-vue/src/element-plus/field/DataProcessForm.vue
<template>
  <div>
    <h2 style="margin-bottom: 8px;">
      Element Plus Field 组件 - 数据处理
    </h2>
    <p style="color: #909399; margin-bottom: 20px; font-size: 14px;">
      千分位解析 / 货币格式化 / 提交路径映射 / 隐藏字段排除 / 空值处理 / 脏检测 / 值变化日志
    </p>

    <!-- 脏检测指示 -->
    <ElAlert
      :title="isDirty ? '表单已修改（未保存）' : '表单未修改'"
      :type="isDirty ? 'warning' : 'success'"
      :closable="false" show-icon style="margin-bottom: 20px;"
    />

    <FormProvider :form="form">
      <form @submit.prevent="handleSubmit">
        <ElCard shadow="never" style="margin-bottom: 20px;">
          <template #header>
            <span style="font-weight: 600;">值解析与转换</span>
          </template>

          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px;">
            <FormField v-slot="{ field }" name="amount">
              <ElFormItem :label="field.label">
                <ElInput
                  :model-value="String(field.value)"
                  placeholder="输入如 1,000"
                  @update:model-value="field.setValue($event)"
                />
                <div style="font-size: 12px; color: #909399; margin-top: 4px;">
                  实际存储: {{ field.value }} | 提交值（分）: {{ (Number(field.value) || 0) * 100 }}
                </div>
              </ElFormItem>
            </FormField>

            <FormField v-slot="{ field }" name="formattedPrice">
              <ElFormItem :label="field.label">
                <ElInput
                  :model-value="String(field.value)"
                  placeholder="输入数字"
                  @update:model-value="field.setValue($event)"
                />
                <div style="font-size: 12px; color: #909399; margin-top: 4px;">
                  格式化显示: <ElTag v-if="field.format" size="small">
                    {{ field.format(field.value) || '—' }}
                  </ElTag>
                </div>
              </ElFormItem>
            </FormField>
          </div>
        </ElCard>

        <ElCard shadow="never" style="margin-bottom: 20px;">
          <template #header>
            <span style="font-weight: 600;">路径映射 <ElTag size="small" type="info">firstName → user.firstName</ElTag></span>
          </template>

          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px;">
            <FormField v-slot="{ field }" name="firstName">
              <ElFormItem :label="field.label">
                <ElInput
                  :model-value="(field.value as string)"
                  placeholder="请输入名"
                  @update:model-value="field.setValue($event)"
                />
              </ElFormItem>
            </FormField>
            <FormField v-slot="{ field }" name="lastName">
              <ElFormItem :label="field.label">
                <ElInput
                  :model-value="(field.value as string)"
                  placeholder="请输入姓"
                  @update:model-value="field.setValue($event)"
                />
              </ElFormItem>
            </FormField>
          </div>
        </ElCard>

        <ElCard shadow="never" style="margin-bottom: 20px;">
          <template #header>
            <span style="font-weight: 600;">空值与备注</span>
          </template>
          <FormField v-slot="{ field }" name="remark">
            <ElFormItem :label="field.label" :extra="field.description">
              <ElInput
                type="textarea" :rows="2"
                :model-value="(field.value as string)"
                placeholder="空字符串提交时排除"
                @update:model-value="field.setValue($event)"
              />
            </ElFormItem>
          </FormField>
        </ElCard>

        <div style="display: flex; gap: 12px; margin-bottom: 20px;">
          <ElButton type="primary" native-type="submit">
            提交
          </ElButton>
          <ElButton @click="form.reset()">
            重置
          </ElButton>
        </div>
      </form>
    </FormProvider>

    <!-- 值变化日志 -->
    <ElCard v-if="changeLog.length > 0" shadow="never" style="margin-bottom: 20px;">
      <template #header>
        <strong>值变化日志（最近 8 条）</strong>
      </template>
      <div style="font-family: monospace; font-size: 12px; max-height: 200px; overflow-y: auto;">
        <div v-for="(log, i) in changeLog" :key="i" style="padding: 2px 0; color: #606266; border-bottom: 1px solid #f0f0f0;">
          {{ log }}
        </div>
      </div>
    </ElCard>

    <ElCard v-if="submitResult" shadow="never">
      <template #header>
        <strong>提交数据（注意路径映射和值转换）</strong>
      </template>
      <pre style="margin: 0; white-space: pre-wrap; font-size: 13px;">{{ submitResult }}</pre>
    </ElCard>
  </div>
</template>

<script setup lang="ts">
import { setupElementPlus } from '@moluoxixi/ui-element-plus'
import { FormField, FormProvider, useCreateForm } from '@moluoxixi/vue'
import {
  ElAlert,
  ElButton,
  ElCard,
  ElFormItem,
  ElInput,
  ElTag,
} from 'element-plus'
/**
 * Element Plus Field 组件模式 - 数据处理
 *
 * 覆盖场景：
 * - 值格式化（format）：存数字 → 显示货币
 * - 值解析（parse）：用户输入 "1,000" → 存储 1000
 * - 提交前数据转换（transform）：金额元→分
 * - 路径映射（submitPath）：UI 路径 → 提交路径不同
 * - 隐藏字段排除（excludeWhenHidden）
 * - 空值策略（trim 空字符串）
 * - 值变化监听
 * - 表单脏检测
 */
import { computed, ref } from 'vue'
import 'element-plus/dist/index.css'

setupElementPlus()

const form = useCreateForm({
  initialValues: {
    amount: 0,
    formattedPrice: '',
    firstName: '',
    lastName: '',
    secretField: '隐藏内部值',
    remark: '',
  },
})

/* 解析：输入千分位 → 存储数字 */
form.createField({
  name: 'amount',
  label: '金额（千分位输入）',
  parse: (input: unknown) => {
    const str = String(input).replace(/,/g, '')
    return Number(str) || 0
  },
  /* 提交转换：元→分 */
  transform: (value: unknown) => Math.round(Number(value) * 100),
})

/* 格式化显示 */
form.createField({
  name: 'formattedPrice',
  label: '格式化价格',
  description: '输入数字，自动格式化为货币显示',
  format: (value: unknown) => {
    const num = Number(value)
    if (Number.isNaN(num) || num === 0)
      return ''
    return num.toLocaleString('zh-CN', { style: 'currency', currency: 'CNY' })
  },
  parse: (input: unknown) => {
    const str = String(input).replace(/[¥,\s]/g, '')
    return Number(str) || 0
  },
})

/* 路径映射：提交时 firstName → user.firstName */
form.createField({ name: 'firstName', label: '名', submitPath: 'user.firstName' })
form.createField({ name: 'lastName', label: '姓', submitPath: 'user.lastName' })

/* 隐藏字段排除 */
form.createField({
  name: 'secretField',
  label: '内部字段（隐藏）',
  visible: false,
  excludeWhenHidden: true,
})

/* 空值策略 */
form.createField({
  name: 'remark',
  label: '备注',
  description: '空字符串提交时排除',
  transform: (value: unknown) => {
    const str = String(value).trim()
    return str || undefined
  },
})

/* 值变化日志 */
const changeLog = ref<string[]>([])
form.onValuesChange((values) => {
  changeLog.value.push(`[${new Date().toLocaleTimeString()}] ${JSON.stringify(values)}`)
  if (changeLog.value.length > 8)
    changeLog.value.shift()
})

/* 脏检测 */
const isDirty = computed(() => form.modified)

const submitResult = ref('')

async function handleSubmit(): Promise<void> {
  const result = await form.submit()
  submitResult.value = JSON.stringify(result.values, null, 2)
}
</script>
