// playground-react/src/antd/field/JsonEditorForm.tsx
/**
 * 场景 33：JSON 编辑器
 *
 * 覆盖：
 * - JSON 编辑 + 格式化 + 验证
 * - 实时语法检查
 * - 三种模式切换
 *
 * 注：实际项目可接入 vanilla-jsoneditor
 */
import React, { useState, useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Button, Typography, Alert, Segmented, Form, Input, Space, Tag } from 'antd';
import type { FieldInstance } from '@moluoxixi/core';
import type { FieldPattern } from '@moluoxixi/shared';

const { Title, Paragraph, Text } = Typography;

setupAntd();

const MODE_OPTIONS = [
  { label: '编辑态', value: 'editable' },
  { label: '阅读态', value: 'readOnly' },
  { label: '禁用态', value: 'disabled' },
];

const DEFAULT_JSON = JSON.stringify({ name: '张三', age: 28, roles: ['admin', 'editor'], settings: { theme: 'dark', language: 'zh-CN' } }, null, 2);

/** 校验 JSON 字符串 */
function validateJson(str: string): { valid: boolean; error?: string } {
  try { JSON.parse(str); return { valid: true }; }
  catch (e) { return { valid: false, error: (e as Error).message }; }
}

export const JsonEditorForm = observer((): React.ReactElement => {
  const [mode, setMode] = useState<FieldPattern>('editable');
  const [result, setResult] = useState('');
  const [jsonError, setJsonError] = useState<string | null>(null);

  const form = useCreateForm({ initialValues: { configName: 'API 配置', jsonContent: DEFAULT_JSON } });

  useEffect(() => {
    form.createField({ name: 'configName', label: '配置名称', required: true });
    form.createField({ name: 'jsonContent', label: 'JSON 内容', required: true });
  }, []);

  const switchMode = (p: FieldPattern): void => {
    setMode(p);
    ['configName', 'jsonContent'].forEach((n) => { const f = form.getField(n); if (f) f.pattern = p; });
  };

  const handleJsonChange = (field: FieldInstance, value: string): void => {
    field.setValue(value);
    const check = validateJson(value);
    setJsonError(check.valid ? null : check.error ?? null);
  };

  /** 格式化 JSON */
  const formatJson = (): void => {
    const field = form.getField('jsonContent');
    if (!field) return;
    try {
      const parsed = JSON.parse(field.value as string);
      field.setValue(JSON.stringify(parsed, null, 2));
      setJsonError(null);
    } catch {
      /* 格式化失败，保持原样 */
    }
  };

  /** 压缩 JSON */
  const minifyJson = (): void => {
    const field = form.getField('jsonContent');
    if (!field) return;
    try {
      const parsed = JSON.parse(field.value as string);
      field.setValue(JSON.stringify(parsed));
      setJsonError(null);
    } catch {
      /* 压缩失败 */
    }
  };

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    if (jsonError) { setResult('验证失败: JSON 格式错误'); return; }
    const res = await form.submit();
    if (res.errors.length > 0) { setResult('验证失败: ' + res.errors.map((err) => err.message).join(', ')); }
    else { setResult(JSON.stringify(res.values, null, 2)); }
  };

  return (
    <div>
      <Title level={3}>JSON 编辑器</Title>
      <Paragraph type="secondary">JSON 编辑 + 格式化 + 压缩 + 实时语法检查</Paragraph>
      <Segmented value={mode} onChange={(v) => switchMode(v as FieldPattern)} options={MODE_OPTIONS} style={{ marginBottom: 16 }} />

      <FormProvider form={form}>
        <form onSubmit={handleSubmit} noValidate>
          <FormField name="configName">
            {(field: FieldInstance) => (
              <Form.Item label={field.label} required={field.required}>
                <Input value={(field.value as string) ?? ''} onChange={(e) => field.setValue(e.target.value)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} />
              </Form.Item>
            )}
          </FormField>

          <FormField name="jsonContent">
            {(field: FieldInstance) => (
              <Form.Item
                label={<Space>{field.label} {jsonError ? <Tag color="error">语法错误</Tag> : <Tag color="success">合法 JSON</Tag>}</Space>}
                required={field.required}
                validateStatus={jsonError ? 'error' : undefined}
                help={jsonError}
              >
                {mode === 'editable' ? (
                  <>
                    <Space style={{ marginBottom: 8 }}>
                      <Button size="small" onClick={formatJson}>格式化</Button>
                      <Button size="small" onClick={minifyJson}>压缩</Button>
                    </Space>
                    <Input.TextArea
                      value={(field.value as string) ?? ''}
                      onChange={(e) => handleJsonChange(field, e.target.value)}
                      rows={14}
                      style={{ fontFamily: 'Consolas, Monaco, monospace', fontSize: 13 }}
                    />
                  </>
                ) : (
                  <pre style={{ padding: 16, borderRadius: 8, background: '#f6f8fa', fontSize: 13, fontFamily: 'Consolas, Monaco, monospace', overflow: 'auto', maxHeight: 400, opacity: mode === 'disabled' ? 0.6 : 1 }}>
                    {(field.value as string) || '{}'}
                  </pre>
                )}
              </Form.Item>
            )}
          </FormField>

          {mode === 'editable' && <Button type="primary" htmlType="submit">提交</Button>}
        </form>
      </FormProvider>

      {result && (<Alert style={{ marginTop: 16 }} type={result.startsWith('验证失败') ? 'error' : 'success'} message="提交结果" description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>} />)}
    </div>
  );
});

// playground-vue/src/element-plus/field/JsonEditorForm.vue
<template>
  <div>
    <h2>JSON 编辑器</h2>
    <p style="color: #909399; margin-bottom: 16px; font-size: 14px;">JSON 编辑 + 格式化 + 实时语法检查</p>
    <el-radio-group v-model="mode" size="small" style="margin-bottom: 16px">
      <el-radio-button v-for="opt in MODE_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</el-radio-button>
    </el-radio-group>
    <FormProvider :form="form">
      <form @submit.prevent="handleSubmit" novalidate>
        <FormField v-slot="{ field }" name="configName"><el-form-item :label="field.label"><el-input :model-value="(field.value as string) ?? ''" @update:model-value="field.setValue($event)" :disabled="mode === 'disabled'" /></el-form-item></FormField>
        <FormField v-slot="{ field }" name="jsonContent">
          <el-form-item :label="field.label">
            <el-space v-if="mode === 'editable'" style="margin-bottom: 8px"><el-button size="small" @click="formatJson(field)">格式化</el-button><el-button size="small" @click="minifyJson(field)">压缩</el-button><el-tag :type="jsonError ? 'danger' : 'success'">{{ jsonError ? '语法错误' : '合法 JSON' }}</el-tag></el-space>
            <el-input v-if="mode === 'editable'" type="textarea" :model-value="(field.value as string) ?? ''" @update:model-value="handleJsonChange(field, $event)" :rows="14" :style="{ fontFamily: 'Consolas, Monaco, monospace', fontSize: '13px' }" />
            <pre v-else :style="{ padding: '16px', borderRadius: '8px', background: '#f6f8fa', fontSize: '13px', fontFamily: 'Consolas, Monaco, monospace', overflow: 'auto', maxHeight: '400px', opacity: mode === 'disabled' ? 0.6 : 1 }">{{ (field.value as string) || '{}' }}</pre>
            <div v-if="jsonError" style="color: #f56c6c; font-size: 12px; margin-top: 4px">{{ jsonError }}</div>
          </el-form-item>
        </FormField>
        <el-button v-if="mode === 'editable'" type="primary" native-type="submit">提交</el-button>
      </form>
    </FormProvider>
    <el-alert v-if="result" :type="result.startsWith('验证失败') ? 'error' : 'success'" :description="result" show-icon style="margin-top: 16px" />
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/vue'
import { setupElementPlus } from '@moluoxixi/ui-element-plus'
import { ElButton, ElSpace, ElAlert, ElRadioGroup, ElRadioButton, ElInput, ElFormItem, ElTag } from 'element-plus'
import type { FieldInstance } from '@moluoxixi/core'
import type { FieldPattern } from '@moluoxixi/shared'
setupElementPlus()
const MODE_OPTIONS = [{ label: '编辑态', value: 'editable' }, { label: '阅读态', value: 'readOnly' }, { label: '禁用态', value: 'disabled' }]
const mode = ref<FieldPattern>('editable')
const result = ref('')
const jsonError = ref<string | null>(null)
const form = useCreateForm({ initialValues: { configName: 'API 配置', jsonContent: JSON.stringify({ name: '张三', age: 28, roles: ['admin'] }, null, 2) } })
onMounted(() => { form.createField({ name: 'configName', label: '配置名称', required: true }); form.createField({ name: 'jsonContent', label: 'JSON 内容', required: true }) })
function handleJsonChange(field: FieldInstance, value: string): void { field.setValue(value); try { JSON.parse(value); jsonError.value = null } catch (e) { jsonError.value = (e as Error).message } }
function formatJson(field: FieldInstance): void { try { field.setValue(JSON.stringify(JSON.parse(field.value as string), null, 2)); jsonError.value = null } catch { /* */ } }
function minifyJson(field: FieldInstance): void { try { field.setValue(JSON.stringify(JSON.parse(field.value as string))); jsonError.value = null } catch { /* */ } }
async function handleSubmit(): Promise<void> { if (jsonError.value) { result.value = '验证失败: JSON 格式错误'; return }; const res = await form.submit(); result.value = res.errors.length > 0 ? '验证失败: ' + res.errors.map(e => e.message).join(', ') : JSON.stringify(res.values, null, 2) }
</script>
