// playground-react/src/antd/field/MapPickerForm.tsx
/**
 * 场景 30：地图选点
 *
 * 覆盖：
 * - 地图选点集成（模拟实现，实际可接入 react-amap）
 * - 经纬度坐标同步
 * - 地址反查
 * - 三种模式切换
 */
import React, { useState, useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Button, Typography, Alert, Segmented, Form, Input, InputNumber, Space } from 'antd';
import { EnvironmentOutlined } from '@ant-design/icons';
import type { FieldInstance } from '@moluoxixi/core';
import type { FieldPattern } from '@moluoxixi/shared';

const { Title, Paragraph, Text } = Typography;

setupAntd();

const MODE_OPTIONS = [
  { label: '编辑态', value: 'editable' },
  { label: '阅读态', value: 'readOnly' },
  { label: '禁用态', value: 'disabled' },
];

/** 模拟地图选点组件（实际项目中替换为 react-amap 组件） */
const MapPicker = observer(({
  lng,
  lat,
  onChange,
  disabled,
}: {
  lng: number;
  lat: number;
  onChange: (lng: number, lat: number) => void;
  disabled: boolean;
}): React.ReactElement => {
  /** 模拟点击地图选点 */
  const handleMapClick = (e: React.MouseEvent<HTMLDivElement>): void => {
    if (disabled) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    /* 将像素映射到经纬度范围 */
    const newLng = 73 + (x / rect.width) * (135 - 73);
    const newLat = 53 - (y / rect.height) * (53 - 3);
    onChange(Math.round(newLng * 10000) / 10000, Math.round(newLat * 10000) / 10000);
  };

  /* 将经纬度映射到像素位置 */
  const markerX = ((lng - 73) / (135 - 73)) * 100;
  const markerY = ((53 - lat) / (53 - 3)) * 100;

  return (
    <div
      onClick={handleMapClick}
      style={{
        width: '100%',
        height: 300,
        background: 'linear-gradient(135deg, #e0f7fa 0%, #b2dfdb 50%, #a5d6a7 100%)',
        borderRadius: 8,
        border: '1px solid #d9d9d9',
        position: 'relative',
        cursor: disabled ? 'not-allowed' : 'crosshair',
        overflow: 'hidden',
        opacity: disabled ? 0.6 : 1,
      }}
    >
      {/* 网格线 */}
      <svg style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }}>
        {Array.from({ length: 10 }, (_, i) => (
          <React.Fragment key={i}>
            <line x1={`${i * 10}%`} y1="0" x2={`${i * 10}%`} y2="100%" stroke="#00000010" />
            <line x1="0" y1={`${i * 10}%`} x2="100%" y2={`${i * 10}%`} stroke="#00000010" />
          </React.Fragment>
        ))}
      </svg>

      {/* 标记点 */}
      <div style={{
        position: 'absolute',
        left: `${markerX}%`,
        top: `${markerY}%`,
        transform: 'translate(-50%, -100%)',
        transition: 'all 0.2s',
      }}>
        <EnvironmentOutlined style={{ fontSize: 32, color: '#ff4d4f' }} />
      </div>

      {/* 坐标信息 */}
      <div style={{ position: 'absolute', bottom: 8, right: 8, background: 'rgba(255,255,255,0.9)', padding: '4px 8px', borderRadius: 4, fontSize: 12 }}>
        经度: {lng.toFixed(4)} | 纬度: {lat.toFixed(4)}
      </div>

      {!disabled && (
        <div style={{ position: 'absolute', top: 8, left: 8, background: 'rgba(255,255,255,0.9)', padding: '4px 8px', borderRadius: 4, fontSize: 12 }}>
          点击选择位置（模拟中国地图范围）
        </div>
      )}
    </div>
  );
});

export const MapPickerForm = observer((): React.ReactElement => {
  const [mode, setMode] = useState<FieldPattern>('editable');
  const [result, setResult] = useState('');

  const form = useCreateForm({
    initialValues: { locationName: '天安门广场', lng: 116.3912, lat: 39.9075, address: '北京市东城区' },
  });

  useEffect(() => {
    form.createField({ name: 'locationName', label: '地点名称', required: true });
    form.createField({ name: 'lng', label: '经度', required: true });
    form.createField({ name: 'lat', label: '纬度', required: true });
    form.createField({ name: 'address', label: '详细地址' });
  }, []);

  const switchMode = (p: FieldPattern): void => {
    setMode(p);
    ['locationName', 'lng', 'lat', 'address'].forEach((n) => { const f = form.getField(n); if (f) f.pattern = p; });
  };

  const handleMapChange = (lng: number, lat: number): void => {
    form.setFieldValue('lng', lng);
    form.setFieldValue('lat', lat);
    form.setFieldValue('address', `经度 ${lng}，纬度 ${lat} 附近`);
  };

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    const res = await form.submit();
    if (res.errors.length > 0) { setResult('验证失败: ' + res.errors.map((err) => err.message).join(', ')); }
    else { setResult(JSON.stringify(res.values, null, 2)); }
  };

  return (
    <div>
      <Title level={3}>地图选点</Title>
      <Paragraph type="secondary">模拟地图选点（实际项目可接入 react-amap） / 经纬度同步 / 三种模式</Paragraph>

      <Alert type="info" showIcon style={{ marginBottom: 16 }} message="此为模拟地图，点击区域可选点。实际项目请安装 react-amap 并接入高德地图 API。" />

      <Segmented value={mode} onChange={(v) => switchMode(v as FieldPattern)} options={MODE_OPTIONS} style={{ marginBottom: 16 }} />

      <FormProvider form={form}>
        <form onSubmit={handleSubmit} noValidate>
          <FormField name="locationName">
            {(field: FieldInstance) => (
              <Form.Item label={field.label} required={field.required}>
                <Input value={(field.value as string) ?? ''} onChange={(e) => field.setValue(e.target.value)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} />
              </Form.Item>
            )}
          </FormField>

          <Form.Item label="地图选点">
            <MapPicker
              lng={(form.getFieldValue('lng') as number) ?? 116}
              lat={(form.getFieldValue('lat') as number) ?? 39}
              onChange={handleMapChange}
              disabled={mode !== 'editable'}
            />
          </Form.Item>

          <Space style={{ marginBottom: 16 }}>
            <FormField name="lng">
              {(field: FieldInstance) => (
                <Form.Item label="经度" style={{ marginBottom: 0 }}>
                  <InputNumber value={field.value as number} onChange={(v) => field.setValue(v)} disabled={mode !== 'editable'} style={{ width: 150 }} step={0.0001} />
                </Form.Item>
              )}
            </FormField>
            <FormField name="lat">
              {(field: FieldInstance) => (
                <Form.Item label="纬度" style={{ marginBottom: 0 }}>
                  <InputNumber value={field.value as number} onChange={(v) => field.setValue(v)} disabled={mode !== 'editable'} style={{ width: 150 }} step={0.0001} />
                </Form.Item>
              )}
            </FormField>
          </Space>

          <FormField name="address">
            {(field: FieldInstance) => (
              <Form.Item label={field.label}>
                <Input value={(field.value as string) ?? ''} onChange={(e) => field.setValue(e.target.value)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} />
              </Form.Item>
            )}
          </FormField>

          {mode === 'editable' && <Button type="primary" htmlType="submit">提交</Button>}
        </form>
      </FormProvider>

      {result && (<Alert style={{ marginTop: 16 }} type={result.startsWith('验证失败') ? 'error' : 'success'} message="提交结果" description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>} />)}
    </div>
  );
});

// playground-vue/src/element-plus/field/MapPickerForm.vue
<template>
  <div>
    <h2>地图选点</h2>
    <p style="color: #909399; margin-bottom: 16px; font-size: 14px;">模拟地图选点（可接入 @vuemap/vue-amap）</p>
    <el-alert type="info" show-icon style="margin-bottom: 16px" title="此为模拟地图，点击区域可选点。" />
    <el-radio-group v-model="mode" size="small" style="margin-bottom: 16px">
      <el-radio-button v-for="opt in MODE_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</el-radio-button>
    </el-radio-group>
    <FormProvider :form="form">
      <form @submit.prevent="handleSubmit" novalidate>
        <FormField v-slot="{ field }" name="locationName"><el-form-item :label="field.label"><el-input :model-value="(field.value as string) ?? ''" @update:model-value="field.setValue($event)" :disabled="mode === 'disabled'" /></el-form-item></FormField>
        <el-form-item label="地图选点">
          <div @click="handleMapClick" :style="{ width: '100%', height: '300px', background: 'linear-gradient(135deg, #e0f7fa, #a5d6a7)', borderRadius: '8px', border: '1px solid #dcdfe6', position: 'relative', cursor: mode !== 'editable' ? 'not-allowed' : 'crosshair', opacity: mode === 'disabled' ? 0.6 : 1 }">
            <div :style="{ position: 'absolute', left: `${((lng - 73) / 62) * 100}%`, top: `${((53 - lat) / 50) * 100}%`, transform: 'translate(-50%, -100%)', transition: 'all 0.2s', fontSize: '32px', color: '#f56c6c' }">📍</div>
            <div style="position: absolute; bottom: 8px; right: 8px; background: rgba(255,255,255,0.9); padding: 4px 8px; border-radius: 4px; font-size: 12px">经度: {{ lng.toFixed(4) }} | 纬度: {{ lat.toFixed(4) }}</div>
          </div>
        </el-form-item>
        <el-space style="margin-bottom: 16px">
          <FormField v-slot="{ field }" name="lng"><el-form-item label="经度" style="margin-bottom: 0"><el-input-number :model-value="(field.value as number)" @update:model-value="field.setValue($event)" :disabled="mode !== 'editable'" :step="0.0001" style="width: 150px" /></el-form-item></FormField>
          <FormField v-slot="{ field }" name="lat"><el-form-item label="纬度" style="margin-bottom: 0"><el-input-number :model-value="(field.value as number)" @update:model-value="field.setValue($event)" :disabled="mode !== 'editable'" :step="0.0001" style="width: 150px" /></el-form-item></FormField>
        </el-space>
        <el-button v-if="mode === 'editable'" type="primary" native-type="submit">提交</el-button>
      </form>
    </FormProvider>
    <el-alert v-if="result" :type="result.startsWith('验证失败') ? 'error' : 'success'" :description="result" show-icon style="margin-top: 16px" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/vue'
import { setupElementPlus } from '@moluoxixi/ui-element-plus'
import { ElButton, ElSpace, ElAlert, ElRadioGroup, ElRadioButton, ElInput, ElInputNumber, ElFormItem } from 'element-plus'
import type { FieldPattern } from '@moluoxixi/shared'

setupElementPlus()
const MODE_OPTIONS = [{ label: '编辑态', value: 'editable' }, { label: '阅读态', value: 'readOnly' }, { label: '禁用态', value: 'disabled' }]
const mode = ref<FieldPattern>('editable')
const result = ref('')
const form = useCreateForm({ initialValues: { locationName: '天安门广场', lng: 116.3912, lat: 39.9075 } })
const lng = computed(() => (form.getFieldValue('lng') as number) ?? 116)
const lat = computed(() => (form.getFieldValue('lat') as number) ?? 39)

onMounted(() => { form.createField({ name: 'locationName', label: '地点名称', required: true }); form.createField({ name: 'lng', label: '经度' }); form.createField({ name: 'lat', label: '纬度' }) })
function handleMapClick(e: MouseEvent): void { if (mode.value !== 'editable') return; const rect = (e.currentTarget as HTMLDivElement).getBoundingClientRect(); const x = e.clientX - rect.left; const y = e.clientY - rect.top; form.setFieldValue('lng', Math.round((73 + (x / rect.width) * 62) * 10000) / 10000); form.setFieldValue('lat', Math.round((53 - (y / rect.height) * 50) * 10000) / 10000) }
async function handleSubmit(): Promise<void> { const res = await form.submit(); result.value = res.errors.length > 0 ? '验证失败: ' + res.errors.map(e => e.message).join(', ') : JSON.stringify(res.values, null, 2) }
</script>
