// playground-react/src/antd/field/LifecycleForm.tsx
/**
 * 场景 44：生命周期钩子
 *
 * 覆盖：
 * - onMount：表单挂载
 * - onChange：值变化监听
 * - onSubmit：提交拦截
 * - onReset：重置拦截
 * - 自动保存（防抖）
 * - 事件日志面板
 * - 三种模式切换
 */
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import {
  Button, Typography, Alert, Segmented, Form, Input, InputNumber, Space, Tag, Card, Badge, Switch,
} from 'antd';
import type { FieldInstance } from '@moluoxixi/core';
import type { FieldPattern } from '@moluoxixi/shared';

const { Title, Paragraph, Text } = Typography;

setupAntd();

const MODE_OPTIONS = [
  { label: '编辑态', value: 'editable' },
  { label: '阅读态', value: 'readOnly' },
  { label: '禁用态', value: 'disabled' },
];

const FIELDS = ['title', 'price', 'description'];

/** 自动保存防抖时间（ms） */
const AUTO_SAVE_DELAY = 1500;

interface LogEntry {
  id: number;
  time: string;
  type: 'mount' | 'change' | 'submit' | 'reset' | 'auto-save';
  message: string;
}

let logId = 0;

export const LifecycleForm = observer((): React.ReactElement => {
  const [mode, setMode] = useState<FieldPattern>('editable');
  const [result, setResult] = useState('');
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [autoSave, setAutoSave] = useState(true);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const form = useCreateForm({
    initialValues: { title: '生命周期测试', price: 99, description: '' },
  });

  /** 添加日志 */
  const addLog = useCallback((type: LogEntry['type'], msg: string): void => {
    logId += 1;
    setLogs((prev) => [{ id: logId, time: new Date().toLocaleTimeString(), type, message: msg }, ...prev].slice(0, 50));
  }, []);

  useEffect(() => {
    form.createField({ name: 'title', label: '标题', required: true });
    form.createField({ name: 'price', label: '价格' });
    form.createField({ name: 'description', label: '描述' });

    /* onMount */
    addLog('mount', '表单已挂载');

    /* onChange：监听值变化 */
    const unsub = form.onValuesChange((values: Record<string, unknown>) => {
      addLog('change', `值变化：${JSON.stringify(values).slice(0, 80)}...`);

      /* 自动保存（防抖） */
      if (timerRef.current) clearTimeout(timerRef.current);
      if (autoSave) {
        timerRef.current = setTimeout(() => {
          addLog('auto-save', '自动保存到 localStorage');
          try { localStorage.setItem('lifecycle-form-auto', JSON.stringify(values)); } catch { /* ignore */ }
        }, AUTO_SAVE_DELAY);
      }
    });

    return () => {
      unsub();
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [autoSave]);

  const switchMode = (p: FieldPattern): void => {
    setMode(p);
    FIELDS.forEach((n) => { const f = form.getField(n); if (f) f.pattern = p; });
  };

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    addLog('submit', '提交开始');
    const res = await form.submit();
    if (res.errors.length > 0) {
      addLog('submit', '提交失败: ' + res.errors.map((err) => err.message).join(', '));
      setResult('验证失败: ' + res.errors.map((err) => err.message).join(', '));
    } else {
      addLog('submit', '提交成功');
      setResult(JSON.stringify(res.values, null, 2));
    }
  };

  const handleReset = (): void => {
    addLog('reset', '表单已重置');
    form.reset();
  };

  const typeColors: Record<string, string> = { mount: 'purple', change: 'blue', submit: 'green', reset: 'orange', 'auto-save': 'cyan' };

  return (
    <div>
      <Title level={3}>生命周期钩子</Title>
      <Paragraph type="secondary">onMount / onChange / onSubmit / onReset / 自动保存（{AUTO_SAVE_DELAY}ms 防抖）</Paragraph>
      <Segmented value={mode} onChange={(v) => switchMode(v as FieldPattern)} options={MODE_OPTIONS} style={{ marginBottom: 16 }} />

      <div style={{ display: 'flex', gap: 16 }}>
        <div style={{ flex: 1 }}>
          <Space style={{ marginBottom: 12 }}>
            <Text>自动保存：</Text>
            <Switch checked={autoSave} onChange={(v) => setAutoSave(v)} />
          </Space>

          <FormProvider form={form}>
            <form onSubmit={handleSubmit} noValidate>
              {FIELDS.map((name) => (
                <FormField key={name} name={name}>
                  {(field: FieldInstance) => (
                    <Form.Item label={field.label} required={field.required}>
                      {name === 'price' ? (
                        <InputNumber value={field.value as number} onChange={(v) => field.setValue(v)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} style={{ width: '100%' }} />
                      ) : name === 'description' ? (
                        <Input.TextArea value={(field.value as string) ?? ''} onChange={(e) => field.setValue(e.target.value)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} rows={3} />
                      ) : (
                        <Input value={(field.value as string) ?? ''} onChange={(e) => field.setValue(e.target.value)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} />
                      )}
                    </Form.Item>
                  )}
                </FormField>
              ))}
              {mode === 'editable' && (
                <Space>
                  <Button type="primary" htmlType="submit">提交</Button>
                  <Button onClick={handleReset}>重置</Button>
                </Space>
              )}
            </form>
          </FormProvider>
        </div>

        {/* 事件日志面板 */}
        <Card title={<span>事件日志 <Badge count={logs.length} /></span>} size="small" style={{ width: 360 }}
          extra={<Button size="small" onClick={() => setLogs([])}>清空</Button>}
        >
          <div style={{ maxHeight: 400, overflow: 'auto', fontSize: 12 }}>
            {logs.map((log) => (
              <div key={log.id} style={{ padding: '2px 0', borderBottom: '1px solid #f0f0f0' }}>
                <Tag color={typeColors[log.type] ?? 'default'} style={{ fontSize: 10 }}>{log.type}</Tag>
                <Text type="secondary">{log.time}</Text>
                <div style={{ color: '#555', marginTop: 2 }}>{log.message}</div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {result && (<Alert style={{ marginTop: 16 }} type={result.startsWith('验证失败') ? 'error' : 'success'} message="提交结果" description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>} />)}
    </div>
  );
});

// playground-vue/src/antd-vue/field/LifecycleForm.vue
<template>
  <div>
    <h2>生命周期钩子</h2>
    <p style="color: rgba(0,0,0,0.45); margin-bottom: 16px; font-size: 14px;">onMount / onChange / onSubmit / onReset / 自动保存</p>
    <ASegmented v-model:value="mode" :options="MODE_OPTIONS" style="margin-bottom: 16px" />
    <div style="display: flex; gap: 16px">
      <div style="flex: 1">
        <ASpace style="margin-bottom: 12px"><span>自动保存：</span><ASwitch v-model:checked="autoSave" /></ASpace>
        <FormProvider :form="form"><form @submit.prevent="handleSubmit" novalidate>
          <FormField v-for="n in FIELDS" :key="n" v-slot="{ field }" :name="n"><AFormItem :label="field.label">
            <template v-if="mode === 'readOnly'"><span v-if="n === 'description'" style="white-space:pre-wrap">{{ (field.value as string) || '—' }}</span><span v-else>{{ field.value ?? '—' }}</span></template>
            <template v-else><AInputNumber v-if="n === 'price'" :value="(field.value as number)" @update:value="field.setValue($event)" :disabled="mode === 'disabled'" style="width: 100%" />
            <ATextarea v-else-if="n === 'description'" :value="(field.value as string) ?? ''" @update:value="field.setValue($event)" :disabled="mode === 'disabled'" :rows="3" />
            <AInput v-else :value="(field.value as string) ?? ''" @update:value="field.setValue($event)" :disabled="mode === 'disabled'" /></template>
          </AFormItem></FormField>
          <ASpace v-if="mode === 'editable'"><AButton type="primary" html-type="submit">提交</AButton><AButton @click="handleReset">重置</AButton></ASpace>
        </form></FormProvider>
      </div>
      <ACard :title="`事件日志 (${logs.length})`" size="small" style="width: 360px"><template #extra><AButton size="small" @click="logs = []">清空</AButton></template>
        <div style="max-height: 400px; overflow: auto; font-size: 12px"><div v-for="log in logs" :key="log.id" style="padding: 2px 0; border-bottom: 1px solid #f0f0f0"><ATag :color="typeColors[log.type]" style="font-size: 10px">{{ log.type }}</ATag><span style="color: #999">{{ log.time }}</span><div style="color: #555; margin-top: 2px">{{ log.message }}</div></div></div>
      </ACard>
    </div>
    <AAlert v-if="result" :type="result.startsWith('验证失败') ? 'error' : 'success'" message="提交结果" style="margin-top: 16px"><template #description><pre style="margin: 0; white-space: pre-wrap">{{ result }}</pre></template></AAlert>
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/vue'
import { setupAntdVue } from '@moluoxixi/ui-antd-vue'
import { Button as AButton, Space as ASpace, Alert as AAlert, Segmented as ASegmented, Input as AInput, InputNumber as AInputNumber, FormItem as AFormItem, Card as ACard, Textarea as ATextarea, Tag as ATag, Switch as ASwitch } from 'ant-design-vue'
import type { FieldPattern } from '@moluoxixi/shared'
setupAntdVue()
const MODE_OPTIONS = [{ label: '编辑态', value: 'editable' }, { label: '阅读态', value: 'readOnly' }, { label: '禁用态', value: 'disabled' }]
const mode = ref<FieldPattern>('editable')
const result = ref('')
const autoSave = ref(true)
const FIELDS = ['title', 'price', 'description']
interface Log { id: number; time: string; type: string; message: string }
const logs = ref<Log[]>([])
let logId = 0
const typeColors: Record<string, string> = { mount: 'purple', change: 'blue', submit: 'green', reset: 'orange', 'auto-save': 'cyan' }
function addLog(type: string, msg: string): void { logId++; logs.value = [{ id: logId, time: new Date().toLocaleTimeString(), type, message: msg }, ...logs.value].slice(0, 50) }
const form = useCreateForm({ initialValues: { title: '生命周期测试', price: 99, description: '' } })
watch(mode, (v) => { form.pattern = v })
let timer: ReturnType<typeof setTimeout> | null = null
onMounted(() => {
  form.createField({ name: 'title', label: '标题', required: true }); form.createField({ name: 'price', label: '价格' }); form.createField({ name: 'description', label: '描述' })
  addLog('mount', '表单已挂载')
  form.onValuesChange((v: Record<string, unknown>) => {
    addLog('change', `值变化：${JSON.stringify(v).slice(0, 80)}...`)
    if (timer) clearTimeout(timer)
    if (autoSave.value) { timer = setTimeout(() => { addLog('auto-save', '自动保存到 localStorage'); try { localStorage.setItem('vue-lifecycle-auto', JSON.stringify(v)) } catch { /* */ } }, 1500) }
  })
})
onUnmounted(() => { if (timer) clearTimeout(timer) })
function handleReset(): void { addLog('reset', '表单已重置'); form.reset() }
async function handleSubmit(): Promise<void> { addLog('submit', '提交开始'); const res = await form.submit(); if (res.errors.length > 0) { addLog('submit', '提交失败'); result.value = '验证失败: ' + res.errors.map(e => e.message).join(', ') } else { addLog('submit', '提交成功'); result.value = JSON.stringify(res.values, null, 2) } }
</script>
