// playground/vue/src/App.vue
<template>
  <div style="max-width: 1400px; margin: 0 auto; padding: 16px; font-family: system-ui, sans-serif;">
    <h1 style="margin-bottom: 4px;">
      ConfigForm - Vue Playground
    </h1>
    <p style="color: #666; margin-bottom: 16px; font-size: 13px;">
      基于 @vue/reactivity 的响应式配置化表单 · {{ totalScenes }} 个场景 × 2 套 UI 库 · ConfigForm + SchemaField 递归渲染
    </p>

    <!-- UI 库切换 -->
    <div style="display: flex; gap: 8px; margin-bottom: 16px; padding: 8px 16px; background: #f5f5f5; border-radius: 8px;">
      <span style="line-height: 32px; font-weight: 600; color: #333; font-size: 13px;">UI 组件库：</span>
      <button
        v-for="lib in uiLibs" :key="lib.key"
        :style="{ padding: '4px 16px',
                  borderRadius: '6px',
                  cursor: 'pointer',
                  fontSize: '13px',
                  fontWeight: 600,
                  background: currentUI === lib.key ? lib.color : '#fff',
                  color: currentUI === lib.key ? '#fff' : '#333',
                  border: `2px solid ${currentUI === lib.key ? lib.color : '#ddd'}` }"
        @click="currentUI = lib.key"
      >
        {{ lib.label }}
      </button>
    </div>

    <!-- 主体：左侧导航 + 右侧内容 -->
    <div style="display: flex; gap: 16px;">
      <!-- 左侧导航 -->
      <div style="width: 280px; flex-shrink: 0; border: 1px solid #eee; border-radius: 8px; overflow: hidden;">
        <div style="max-height: calc(100vh - 180px); overflow: auto; padding: 8px;">
          <div v-for="group in sceneGroups" :key="group.key" style="margin-bottom: 8px;">
            <div style="font-size: 11px; font-weight: 600; color: #999; padding: 2px 4px;">
              {{ group.label }}
            </div>
            <button v-for="name in group.items" :key="name" :style="navBtnStyle(name)" @click="currentDemo = name">
              {{ name }}
            </button>
          </div>
        </div>
      </div>

      <!-- 右侧内容区 -->
      <div style="flex: 1; border: 1px solid #eee; border-radius: 8px; padding: 24px; background: #fff; min-height: 400px;">
        <SceneRenderer
          v-if="sceneConfig && currentAdapter"
          :key="`${currentDemo}-${currentUI}`"
          :config="sceneConfig"
          :title="sceneTitle"
          :description="sceneDescription"
          :extra-plugins="scenePlugins"
          :status-tabs="currentAdapter.StatusTabs"
        >
          <template #header-extra>
            <div
              v-if="i18nRuntime && localeOptions.length"
              style="display: flex; align-items: center; gap: 8px; margin-bottom: 12px;"
            >
              <span style="font-size: 13px; font-weight: 600; color: #555;">语言：</span>
              <div style="display: flex; gap: 4px;">
                <button
                  v-for="opt in localeOptions"
                  :key="opt.value"
                  :style="{
                    padding: '4px 12px',
                    borderRadius: '4px',
                    cursor: 'pointer',
                    fontSize: '13px',
                    fontWeight: 500,
                    border: locale === opt.value ? '2px solid #1677ff' : '1px solid #d9d9d9',
                    background: locale === opt.value ? '#e6f4ff' : '#fff',
                    color: locale === opt.value ? '#1677ff' : '#333',
                  }"
                  @click="switchLocale(opt.value)"
                >
                  {{ opt.label }}
                </button>
              </div>
            </div>
            <div
              v-if="ioRuntime"
              style="margin-bottom: 12px; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px;"
            >
              <div style="display: flex; align-items: center; flex-wrap: wrap; gap: 8px; margin-bottom: 8px;">
                <span style="font-size: 13px; font-weight: 600; color: #555;">操作：</span>
                <button @click="exportJson">导出 JSON</button>
                <button @click="exportCsv">导出 CSV</button>
                <button @click="openJsonImport">导入 JSON</button>
                <button @click="openCsvImport">导入 CSV</button>
                <label style="font-size: 12px; color: #555;">
                  导入策略：
                  <select v-model="importStrategy">
                    <option value="merge">merge</option>
                    <option value="shallow">shallow</option>
                    <option value="replace">replace</option>
                  </select>
                </label>
                <button @click="printForm">打印预览</button>
                <input
                  ref="jsonFileInput"
                  type="file"
                  accept=".json,application/json"
                  style="display: none;"
                  @change="onJsonFileChange"
                >
                <input
                  ref="csvFileInput"
                  type="file"
                  accept=".csv,text/csv"
                  style="display: none;"
                  @change="onCsvFileChange"
                >
              </div>
              <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 8px;">
                <div>
                  <div style="font-size: 12px; color: #666; margin-bottom: 4px;">JSON 导出预览</div>
                  <textarea
                    :value="exportJsonPreview"
                    readonly
                    rows="8"
                    style="width: 100%; font-family: monospace; font-size: 12px;"
                  />
                </div>
                <div>
                  <div style="font-size: 12px; color: #666; margin-bottom: 4px;">CSV 导出预览</div>
                  <textarea
                    :value="exportCsvPreview"
                    readonly
                    rows="8"
                    style="width: 100%; font-family: monospace; font-size: 12px;"
                  />
                </div>
              </div>
              <div v-if="importPreview" style="border-top: 1px dashed #d0d7de; padding-top: 8px;">
                <div style="font-size: 12px; color: #666; margin-bottom: 4px;">
                  {{ importPreview.type }} 导入预览：可导入 {{ importPreview.appliedKeys.length }} 字段
                  <template v-if="importPreview.skippedKeys.length">
                    ，跳过 {{ importPreview.skippedKeys.join(', ') }}
                  </template>
                </div>
                <textarea
                  :value="importPreview.raw"
                  readonly
                  rows="5"
                  style="width: 100%; font-family: monospace; font-size: 12px; margin-bottom: 8px;"
                />
                <div style="display: flex; gap: 8px;">
                  <button @click="applyImportPreview">应用导入</button>
                  <button @click="clearImportPreview">清空导入预览</button>
                </div>
              </div>
              <div v-if="ioMessage" style="font-size: 12px; color: #666; margin-top: 8px;">{{ ioMessage }}</div>
            </div>
          </template>
        </SceneRenderer>
        <div v-else style="text-align: center; color: #999; padding: 40px;">
          {{ loading ? '加载中...' : '请选择场景' }}
        </div>
      </div>
    </div>

    <!-- DevTools 浮动面板 -->
    <DevToolsFloating />
  </div>
</template>

<script setup lang="ts">
import type { DevToolsPluginAPI } from '@moluoxixi/plugin-devtools'
import type { FormPlugin } from '@moluoxixi/core'
import type { SceneConfig } from '@playground/shared'
import type { UIAdapter, UILib } from './ui'
import { DevToolsPanel } from '@moluoxixi/plugin-devtools-vue'
import { createVueMessageI18nRuntime } from '@moluoxixi/plugin-i18n-vue'
import { createVueFormIORuntime } from '@moluoxixi/plugin-io-vue'
import { registerComponent } from '@moluoxixi/vue'
import { getSceneGroups, sceneRegistry } from '@playground/shared'
import { computed, defineComponent, h, onMounted, onUnmounted, ref, shallowRef, watch } from 'vue'
import { CodeEditor, ColorPicker, CronEditor, PreviewColorPicker, SignaturePad } from './components/custom'
import SceneRenderer from './components/SceneRenderer.vue'
import { adapters } from './ui'

/** 确保全局 Hook 存在（与 plugin 中逻辑一致，保证面板先于插件挂载时也能订阅） */
interface HookType { forms: Map<string, DevToolsPluginAPI>, onChange: (fn: (forms: Map<string, DevToolsPluginAPI>) => void) => () => void }
function getOrCreateHook(): HookType {
  const g = window as unknown as Record<string, unknown>
  if (!g.__CONFIGFORM_DEVTOOLS_HOOK__) {
    const listeners = new Set<(forms: Map<string, DevToolsPluginAPI>) => void>()
    const hook = {
      forms: new Map<string, DevToolsPluginAPI>(),
      register(id: string, api: DevToolsPluginAPI) {
        hook.forms.set(id, api)
        listeners.forEach(fn => fn(hook.forms))
      },
      unregister(id: string) {
        hook.forms.delete(id)
        listeners.forEach(fn => fn(hook.forms))
      },
      onChange(fn: (forms: Map<string, DevToolsPluginAPI>) => void) {
        listeners.add(fn)
        return () => listeners.delete(fn)
      },
    }
    g.__CONFIGFORM_DEVTOOLS_HOOK__ = hook
  }
  return g.__CONFIGFORM_DEVTOOLS_HOOK__ as HookType
}

/** DevTools 浮动面板包装器：通过全局 Hook 的 onChange 事件驱动更新（零轮询） */
const DevToolsFloating = defineComponent({
  name: 'DevToolsFloating',
  setup() {
    const api = shallowRef<DevToolsPluginAPI | null>(null)
    let dispose: (() => void) | null = null

    onMounted(() => {
      const hook = getOrCreateHook()
      const update = (forms: Map<string, DevToolsPluginAPI>): void => {
        api.value = forms.size > 0 ? forms.values().next().value! : null
      }
      update(hook.forms)
      dispose = hook.onChange(update)
    })

    onUnmounted(() => {
      dispose?.()
    })

    return () => api.value ? h(DevToolsPanel, { api: api.value }) : null
  },
})

const currentUI = ref<UILib>('antd-vue')
const currentDemo = ref('BasicForm')
const loading = ref(false)
const sceneConfig = ref<SceneConfig | null>(null)
const currentAdapter = shallowRef<UIAdapter | null>(null)

registerComponent('ColorPicker', ColorPicker, {
  defaultDecorator: 'FormItem',
  readPrettyComponent: PreviewColorPicker,
})
registerComponent('CronEditor', CronEditor, {
  defaultDecorator: 'FormItem',
})
registerComponent('CodeEditor', CodeEditor)
registerComponent('SignaturePad', SignaturePad)

const uiLibs = [
  { key: 'antd-vue' as UILib, label: 'Ant Design Vue', color: '#1677ff' },
  { key: 'element-plus' as UILib, label: 'Element Plus', color: '#409eff' },
]

const sceneGroups = getSceneGroups()
const totalScenes = sceneGroups.reduce((sum, g) => sum + g.items.length, 0)

/** 切换 UI 库：加载适配器 → 注册组件 → 更新引用 */
async function switchUI(lib: UILib): Promise<void> {
  const adapter = await adapters[lib]()
  adapter.setup()
  currentAdapter.value = adapter
}
switchUI(currentUI.value)
watch(currentUI, switchUI)

/** 加载场景配置（切换场景时先清空，确保 ConfigForm 完全重建） */
async function loadScene(name: string): Promise<void> {
  const entry = sceneRegistry[name]
  if (!entry) {
    sceneConfig.value = null
    return
  }
  sceneConfig.value = null
  loading.value = true
  try {
    sceneConfig.value = (await entry.loader()).default
  }
  catch (e) {
    console.error(`加载场景 ${name} 失败:`, e)
    sceneConfig.value = null
  }
  finally {
    loading.value = false
  }
}
watch(currentDemo, name => loadScene(name), { immediate: true })

const i18nRuntime = shallowRef<ReturnType<typeof createVueMessageI18nRuntime> | undefined>(undefined)
const ioRuntime = shallowRef<ReturnType<typeof createVueFormIORuntime> | undefined>(undefined)
const ioMessage = ref('')
const exportJsonPreview = ref('')
const exportCsvPreview = ref('')
const importStrategy = ref<'merge' | 'shallow' | 'replace'>('merge')
const importPreview = ref<{
  type: 'JSON' | 'CSV'
  raw: string
  data: Record<string, unknown>
  appliedKeys: string[]
  skippedKeys: string[]
} | null>(null)
const jsonFileInput = ref<HTMLInputElement | null>(null)
const csvFileInput = ref<HTMLInputElement | null>(null)
watch(() => sceneConfig.value?.i18n, (config) => {
  if (!config) {
    i18nRuntime.value = undefined
    return
  }
  const messages = Object.fromEntries(
    Object.entries(config.messages).map(([localeKey, values]) => [localeKey, { ...values }]),
  )
  i18nRuntime.value = createVueMessageI18nRuntime({
    messages,
    locale: config.defaultLocale,
  })
}, { immediate: true })
watch(() => currentDemo.value === 'PrintExportForm', (enabled) => {
  ioMessage.value = ''
  importPreview.value = null
  importStrategy.value = 'merge'
  if (!enabled) {
    ioRuntime.value = undefined
    return
  }
  ioRuntime.value = createVueFormIORuntime({
    filenameBase: 'print-export',
    print: {
      title: '打印预览 - PrintExportForm',
    },
  })
}, { immediate: true })
watch(ioRuntime, (runtime, _prev, onCleanup) => {
  if (!runtime) {
    exportJsonPreview.value = ''
    exportCsvPreview.value = ''
    return
  }
  const dispose = runtime.subscribeExportPreview((preview) => {
    exportJsonPreview.value = preview.json
    exportCsvPreview.value = preview.csv
  })
  onCleanup(() => {
    dispose()
  })
}, { immediate: true })
const locale = ref('')
watch(i18nRuntime, (runtime, _prev, onCleanup) => {
  if (!runtime) {
    locale.value = ''
    return
  }
  locale.value = runtime.getLocale()
  const dispose = runtime.subscribeLocale((nextLocale) => {
    locale.value = nextLocale
  })
  onCleanup(() => {
    dispose()
  })
}, { immediate: true })

const localeOptions = computed(() => {
  const config = sceneConfig.value
  if (!config?.i18n)
    return []
  if (config.localeOptions && config.localeOptions.length > 0)
    return config.localeOptions
  return Object.keys(config.i18n.messages).map(key => ({ label: key, value: key }))
})

function translateText(value: string): string {
  const runtime = i18nRuntime.value
  if (!runtime)
    return value
  if (!value.startsWith('$t:'))
    return value
  return runtime.t(value.slice(3))
}

const sceneTitle = computed(() => {
  const config = sceneConfig.value
  if (!config)
    return ''
  void locale.value
  return translateText(config.title)
})

const sceneDescription = computed(() => {
  const config = sceneConfig.value
  if (!config)
    return ''
  void locale.value
  return translateText(config.description)
})

const scenePlugins = computed<FormPlugin[]>(() => {
  const plugins: FormPlugin[] = []
  if (i18nRuntime.value)
    plugins.push(i18nRuntime.value.plugin)
  if (ioRuntime.value)
    plugins.push(ioRuntime.value.plugin)
  return plugins
})

function switchLocale(value: string): void {
  i18nRuntime.value?.setLocale(value)
}

function showImportDone(type: 'JSON' | 'CSV', count: number): void {
  ioMessage.value = `${type} 导入成功：已更新 ${count} 个字段`
}

function showImportError(error: unknown): void {
  const message = error instanceof Error ? error.message : String(error)
  ioMessage.value = `导入失败：${message}`
}

function exportJson(): void {
  ioRuntime.value?.downloadJSON({ filename: 'order-export.json' }).catch(showImportError)
}

function exportCsv(): void {
  ioRuntime.value?.downloadCSV({ filename: 'order-export.csv' }).catch(showImportError)
}

function printForm(): void {
  ioRuntime.value?.print().catch(showImportError)
}

function openJsonImport(): void {
  jsonFileInput.value?.click()
}

function openCsvImport(): void {
  csvFileInput.value?.click()
}

async function onJsonFileChange(event: Event): Promise<void> {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  target.value = ''
  if (!file || !ioRuntime.value)
    return
  try {
    const [raw, result] = await Promise.all([
      file.text(),
      ioRuntime.value.parseImportJSONFile(file, { strategy: importStrategy.value }),
    ])
    importPreview.value = {
      type: 'JSON',
      raw,
      data: result.data,
      appliedKeys: result.appliedKeys,
      skippedKeys: result.skippedKeys,
    }
    ioMessage.value = `JSON 解析完成：可导入 ${result.appliedKeys.length} 个字段`
  }
  catch (error) {
    showImportError(error)
  }
}

async function onCsvFileChange(event: Event): Promise<void> {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  target.value = ''
  if (!file || !ioRuntime.value)
    return
  try {
    const [raw, result] = await Promise.all([
      file.text(),
      ioRuntime.value.parseImportCSVFile(file, { strategy: importStrategy.value }),
    ])
    importPreview.value = {
      type: 'CSV',
      raw,
      data: result.data,
      appliedKeys: result.appliedKeys,
      skippedKeys: result.skippedKeys,
    }
    ioMessage.value = `CSV 解析完成：可导入 ${result.appliedKeys.length} 个字段`
  }
  catch (error) {
    showImportError(error)
  }
}

function applyImportPreview(): void {
  if (!ioRuntime.value || !importPreview.value)
    return
  try {
    const result = ioRuntime.value.applyImport(importPreview.value.data, { strategy: importStrategy.value })
    showImportDone(importPreview.value.type, result.appliedKeys.length)
    importPreview.value = null
  }
  catch (error) {
    showImportError(error)
  }
}

function clearImportPreview(): void {
  importPreview.value = null
}

function navBtnStyle(name: string): Record<string, string> {
  const active = currentDemo.value === name
  const color = currentUI.value === 'antd-vue' ? '#1677ff' : '#409eff'
  return {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    padding: '3px 8px',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '12px',
    background: active ? color : 'transparent',
    color: active ? '#fff' : '#333',
    fontWeight: active ? '600' : '400',
    marginBottom: '1px',
  }
}
</script>

// playground/react/src/App.tsx
import type { DevToolsPluginAPI } from '@moluoxixi/plugin-devtools'
import type { FormPlugin } from '@moluoxixi/core'
/**
 * React Playground 入口
 *
 * 从 @playground/shared 动态加载场景配置，通过 SceneRenderer 渲染。
 */
import type { SceneConfig } from '@playground/shared'
import { DevToolsPanel } from '@moluoxixi/plugin-devtools-react'
import { createReactMessageI18nRuntime } from '@moluoxixi/plugin-i18n-react'
import { createReactFormIORuntime } from '@moluoxixi/plugin-io-react'
import { registerComponent, registerDecorator } from '@moluoxixi/react'
import { setupAntd } from '@moluoxixi/ui-antd'
import { getSceneGroups, sceneRegistry } from '@playground/shared'
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  CardDecorator,
  CodeEditor,
  ColorPicker,
  CronEditor,
  InlineDecorator,
  PreviewColorPicker,
  SignaturePad,
} from './components/custom'
import { SceneRenderer } from './components/SceneRenderer'

/* 注册 Ant Design 基础组件 */
setupAntd()

/*
 * 注册自定义组件 — 覆盖所有注册模式：
 *
 * 1. 有 defaultDecorator（被 FormItem 包裹）
 * 2. 有 readPrettyComponent（阅读态替换为不同组件）
 * 3. 无 defaultDecorator（裸渲染，不被 FormItem 包裹）
 */
registerComponent('ColorPicker', ColorPicker, {
  defaultDecorator: 'FormItem',
  readPrettyComponent: PreviewColorPicker,
})
registerComponent('CronEditor', CronEditor, { defaultDecorator: 'FormItem' })
registerComponent('SignaturePad', SignaturePad) /* 无装饰器，裸渲染 */
registerComponent('CodeEditor', CodeEditor) /* 无装饰器，裸渲染 */

/* 注册自定义装饰器 */
registerDecorator('CardDecorator', CardDecorator)
registerDecorator('InlineDecorator', InlineDecorator)

const sceneGroups = getSceneGroups()
const totalScenes = sceneGroups.reduce((sum, g) => sum + g.items.length, 0)

export function App(): React.ReactElement {
  const [currentDemo, setCurrentDemo] = useState('BasicForm')
  const [sceneConfig, setSceneConfig] = useState<SceneConfig | null>(null)
  const [loading, setLoading] = useState(false)

  const loadScene = useCallback(async (name: string) => {
    const entry = sceneRegistry[name]
    if (!entry) {
      setSceneConfig(null)
      return
    }
    setSceneConfig(null)
    setLoading(true)
    try {
      setSceneConfig((await entry.loader()).default)
    }
    catch (e) {
      console.error(`加载场景 ${name} 失败:`, e)
      setSceneConfig(null)
    }
    finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    loadScene(currentDemo)
  }, [currentDemo, loadScene])

  const i18nConfig = sceneConfig?.i18n
  const isPrintExportScene = currentDemo === 'PrintExportForm'
  const i18nRuntime = useMemo(() => {
    if (!i18nConfig)
      return undefined
    return createReactMessageI18nRuntime({
      messages: i18nConfig.messages,
      locale: i18nConfig.defaultLocale,
    })
  }, [i18nConfig])
  const [locale, setLocale] = useState('')
  const [ioMessage, setIoMessage] = useState('')
  const [exportJsonPreview, setExportJsonPreview] = useState('')
  const [exportCsvPreview, setExportCsvPreview] = useState('')
  const [importStrategy, setImportStrategy] = useState<'merge' | 'shallow' | 'replace'>('merge')
  const [importPreview, setImportPreview] = useState<{
    type: 'JSON' | 'CSV'
    raw: string
    data: Record<string, unknown>
    appliedKeys: string[]
    skippedKeys: string[]
  } | null>(null)
  const jsonFileInputRef = useRef<HTMLInputElement | null>(null)
  const csvFileInputRef = useRef<HTMLInputElement | null>(null)
  const ioRuntime = useMemo(() => {
    if (!isPrintExportScene)
      return undefined
    return createReactFormIORuntime({
      filenameBase: 'print-export',
      print: {
        title: '打印预览 - PrintExportForm',
      },
    })
  }, [isPrintExportScene])

  useEffect(() => {
    if (!i18nRuntime) {
      setLocale('')
      return
    }
    setLocale(i18nRuntime.getLocale())
    return i18nRuntime.subscribeLocale(setLocale)
  }, [i18nRuntime])
  useEffect(() => {
    setIoMessage('')
    setImportPreview(null)
    setImportStrategy('merge')
  }, [currentDemo])
  useEffect(() => {
    if (!ioRuntime) {
      setExportJsonPreview('')
      setExportCsvPreview('')
      return
    }
    return ioRuntime.subscribeExportPreview((preview) => {
      setExportJsonPreview(preview.json)
      setExportCsvPreview(preview.csv)
    })
  }, [ioRuntime])

  const localeOptions = useMemo(() => {
    if (!i18nConfig)
      return []
    if (sceneConfig?.localeOptions && sceneConfig.localeOptions.length > 0)
      return sceneConfig.localeOptions
    return Object.keys(i18nConfig.messages).map(key => ({ label: key, value: key }))
  }, [i18nConfig, sceneConfig?.localeOptions])

  const translateText = useCallback((value: string): string => {
    if (!i18nRuntime)
      return value
    if (!value.startsWith('$t:'))
      return value
    return i18nRuntime.t(value.slice(3))
  }, [i18nRuntime, locale])

  const sceneTitle = useMemo(() => {
    if (!sceneConfig)
      return ''
    return translateText(sceneConfig.title)
  }, [sceneConfig, translateText])
  const sceneDescription = useMemo(() => {
    if (!sceneConfig)
      return ''
    return translateText(sceneConfig.description)
  }, [sceneConfig, translateText])

  const scenePlugins = useMemo<FormPlugin[]>(() => {
    const plugins: FormPlugin[] = []
    if (i18nRuntime)
      plugins.push(i18nRuntime.plugin)
    if (ioRuntime)
      plugins.push(ioRuntime.plugin)
    return plugins
  }, [i18nRuntime, ioRuntime])

  const handleImportDone = useCallback((type: 'JSON' | 'CSV', count: number) => {
    setIoMessage(`${type} 导入成功：已更新 ${count} 个字段`)
  }, [])

  const handleImportError = useCallback((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error)
    setIoMessage(`导入失败：${message}`)
  }, [])

  const onJsonFileChange = useCallback(async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    event.target.value = ''
    if (!file || !ioRuntime)
      return
    try {
      const [raw, result] = await Promise.all([
        file.text(),
        ioRuntime.parseImportJSONFile(file, { strategy: importStrategy }),
      ])
      setImportPreview({
        type: 'JSON',
        raw,
        data: result.data,
        appliedKeys: result.appliedKeys,
        skippedKeys: result.skippedKeys,
      })
      setIoMessage(`JSON 解析完成：可导入 ${result.appliedKeys.length} 个字段`)
    }
    catch (error) {
      handleImportError(error)
    }
  }, [handleImportError, importStrategy, ioRuntime])

  const onCsvFileChange = useCallback(async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    event.target.value = ''
    if (!file || !ioRuntime)
      return
    try {
      const [raw, result] = await Promise.all([
        file.text(),
        ioRuntime.parseImportCSVFile(file, { strategy: importStrategy }),
      ])
      setImportPreview({
        type: 'CSV',
        raw,
        data: result.data,
        appliedKeys: result.appliedKeys,
        skippedKeys: result.skippedKeys,
      })
      setIoMessage(`CSV 解析完成：可导入 ${result.appliedKeys.length} 个字段`)
    }
    catch (error) {
      handleImportError(error)
    }
  }, [handleImportError, importStrategy, ioRuntime])

  const applyImportPreview = useCallback(() => {
    if (!ioRuntime || !importPreview)
      return
    try {
      const result = ioRuntime.applyImport(importPreview.data, { strategy: importStrategy })
      handleImportDone(importPreview.type, result.appliedKeys.length)
      setImportPreview(null)
    }
    catch (error) {
      handleImportError(error)
    }
  }, [handleImportDone, handleImportError, importPreview, importStrategy, ioRuntime])
  const localeSwitcher = i18nRuntime && localeOptions.length > 0
    ? (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
          <span style={{ fontSize: 13, fontWeight: 600, color: '#555' }}>
            语言：
          </span>
          <div style={{ display: 'flex', gap: 4 }}>
            {localeOptions.map(opt => (
              <button
                key={opt.value}
                onClick={() => void i18nRuntime.setLocale(opt.value)}
                style={{
                  padding: '4px 12px',
                  borderRadius: 4,
                  cursor: 'pointer',
                  fontSize: 13,
                  fontWeight: 500,
                  border: locale === opt.value ? '2px solid #1677ff' : '1px solid #d9d9d9',
                  background: locale === opt.value ? '#e6f4ff' : '#fff',
                  color: locale === opt.value ? '#1677ff' : '#333',
                }}
              >
                {opt.label}
              </button>
            ))}
          </div>
        </div>
      )
    : undefined
  const ioToolbar = ioRuntime
    ? (
        <div style={{ marginBottom: 12, border: '1px solid #e5e7eb', borderRadius: 8, padding: 12 }}>
          <div style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginBottom: 8 }}>
            <span style={{ fontSize: 13, fontWeight: 600, color: '#555' }}>
              操作：
            </span>
            <button type="button" onClick={() => { void ioRuntime.downloadJSON({ filename: 'order-export.json' }) }}>导出 JSON</button>
            <button type="button" onClick={() => { void ioRuntime.downloadCSV({ filename: 'order-export.csv' }) }}>导出 CSV</button>
            <button type="button" onClick={() => jsonFileInputRef.current?.click()}>导入 JSON</button>
            <button type="button" onClick={() => csvFileInputRef.current?.click()}>导入 CSV</button>
            <label style={{ fontSize: 12, color: '#555' }}>
              导入策略：
              {' '}
              <select
                value={importStrategy}
                onChange={event => setImportStrategy(event.target.value as 'merge' | 'shallow' | 'replace')}
              >
                <option value="merge">merge</option>
                <option value="shallow">shallow</option>
                <option value="replace">replace</option>
              </select>
            </label>
            <button type="button" onClick={() => { void ioRuntime.print() }}>打印预览</button>
            <input
              ref={jsonFileInputRef}
              type="file"
              accept=".json,application/json"
              style={{ display: 'none' }}
              onChange={onJsonFileChange}
            />
            <input
              ref={csvFileInputRef}
              type="file"
              accept=".csv,text/csv"
              style={{ display: 'none' }}
              onChange={onCsvFileChange}
            />
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 8 }}>
            <div>
              <div style={{ fontSize: 12, color: '#666', marginBottom: 4 }}>JSON 导出预览</div>
              <textarea readOnly rows={8} value={exportJsonPreview} style={{ width: '100%', fontFamily: 'monospace', fontSize: 12 }} />
            </div>
            <div>
              <div style={{ fontSize: 12, color: '#666', marginBottom: 4 }}>CSV 导出预览</div>
              <textarea readOnly rows={8} value={exportCsvPreview} style={{ width: '100%', fontFamily: 'monospace', fontSize: 12 }} />
            </div>
          </div>
          {importPreview
            ? (
                <div style={{ borderTop: '1px dashed #d0d7de', paddingTop: 8 }}>
                  <div style={{ fontSize: 12, color: '#666', marginBottom: 4 }}>
                    {importPreview.type}
                    {' '}
                    导入预览：可导入
                    {' '}
                    {importPreview.appliedKeys.length}
                    {' '}
                    字段
                    {importPreview.skippedKeys.length > 0 ? `，跳过 ${importPreview.skippedKeys.join(', ')}` : ''}
                  </div>
                  <textarea readOnly rows={5} value={importPreview.raw} style={{ width: '100%', fontFamily: 'monospace', fontSize: 12, marginBottom: 8 }} />
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button type="button" onClick={applyImportPreview}>应用导入</button>
                    <button type="button" onClick={() => setImportPreview(null)}>清空导入预览</button>
                  </div>
                </div>
              )
            : null}
          {ioMessage
            ? (
                <div style={{ fontSize: 12, color: '#666', marginTop: 8 }}>
                  {ioMessage}
                </div>
              )
            : null}
        </div>
      )
    : undefined

  return (
    <div style={{ maxWidth: 1400, margin: '0 auto', padding: 16, fontFamily: 'system-ui, sans-serif' }}>
      <h1 style={{ marginBottom: 4 }}>ConfigForm - React Playground</h1>
      <p style={{ color: '#666', marginBottom: 16, fontSize: 13 }}>
        基于 MobX 的响应式配置化表单 ·
        {' '}
        {totalScenes}
        {' '}
        个场景 · Ant Design · ConfigForm + SchemaField 递归渲染
      </p>

      <div style={{ display: 'flex', gap: 8, marginBottom: 16, padding: '8px 16px', background: '#f5f5f5', borderRadius: 8 }}>
        <span style={{ lineHeight: '32px', fontWeight: 600, color: '#333', fontSize: 13 }}>UI 组件库：</span>
        <span style={{ padding: '4px 16px', borderRadius: 6, fontSize: 13, fontWeight: 600, background: '#1677ff', color: '#fff', border: '2px solid #1677ff' }}>
          Ant Design
        </span>
      </div>

      <div style={{ display: 'flex', gap: 16 }}>
        {/* 左侧导航 */}
        <div style={{ width: 280, flexShrink: 0, border: '1px solid #eee', borderRadius: 8, overflow: 'hidden' }}>
          <div style={{ maxHeight: 'calc(100vh - 180px)', overflow: 'auto', padding: 8 }}>
            {sceneGroups.map(group => (
              <div key={group.key} style={{ marginBottom: 8 }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: '#999', padding: '2px 4px' }}>{group.label}</div>
                {group.items.map(name => (
                  <button
                    key={name}
                    onClick={() => setCurrentDemo(name)}
                    style={{ display: 'block', width: '100%', textAlign: 'left', padding: '3px 8px', border: 'none', borderRadius: 4, cursor: 'pointer', fontSize: 12, background: currentDemo === name ? '#1677ff' : 'transparent', color: currentDemo === name ? '#fff' : '#333', fontWeight: currentDemo === name ? 600 : 400, marginBottom: 1 }}
                  >
                    {name}
                  </button>
                ))}
              </div>
            ))}
          </div>
        </div>

        {/* 右侧内容区 */}
        <div style={{ flex: 1, border: '1px solid #eee', borderRadius: 8, padding: 24, background: '#fff', minHeight: 400 }}>
          {sceneConfig
            ? (
                <SceneRenderer
                  key={currentDemo}
                  config={sceneConfig}
                  title={sceneTitle}
                  description={sceneDescription}
                  extraPlugins={scenePlugins}
                  headerExtra={(
                    <>
                      {localeSwitcher}
                      {ioToolbar}
                    </>
                  )}
                />
              )
            : <div style={{ textAlign: 'center', color: '#999', padding: 40 }}>{loading ? '加载中...' : '请选择场景'}</div>}
        </div>
      </div>

      {/* DevTools 浮动面板 — 从全局 Hook 读取 API */}
      <DevToolsFloating />
    </div>
  )
}

/** 确保全局 Hook 存在（与 plugin 中的 ensureGlobalHook 逻辑一致） */
function getOrCreateHook(): { forms: Map<string, DevToolsPluginAPI>, onChange: (fn: (forms: Map<string, DevToolsPluginAPI>) => void) => () => void } {
  const g = window as unknown as Record<string, unknown>
  if (!g.__CONFIGFORM_DEVTOOLS_HOOK__) {
    const listeners = new Set<(forms: Map<string, DevToolsPluginAPI>) => void>()
    g.__CONFIGFORM_DEVTOOLS_HOOK__ = {
      forms: new Map(),
      register(id: string, api: DevToolsPluginAPI) {
        const hook = g.__CONFIGFORM_DEVTOOLS_HOOK__ as { forms: Map<string, DevToolsPluginAPI> }
        hook.forms.set(id, api)
        listeners.forEach(fn => fn(hook.forms))
      },
      unregister(id: string) {
        const hook = g.__CONFIGFORM_DEVTOOLS_HOOK__ as { forms: Map<string, DevToolsPluginAPI> }
        hook.forms.delete(id)
        listeners.forEach(fn => fn(hook.forms))
      },
      onChange(fn: (forms: Map<string, DevToolsPluginAPI>) => void) {
        listeners.add(fn)
        return () => listeners.delete(fn)
      },
    }
  }
  return g.__CONFIGFORM_DEVTOOLS_HOOK__ as ReturnType<typeof getOrCreateHook>
}

/** DevTools 浮动面板包装器：通过全局 Hook 的 onChange 事件驱动更新（零轮询） */
function DevToolsFloating(): React.ReactElement | null {
  const [api, setApi] = useState<DevToolsPluginAPI | null>(null)

  useEffect(() => {
    const hook = getOrCreateHook()
    let disposed = false
    const update = (forms: Map<string, DevToolsPluginAPI>): void => {
      const nextApi = forms.size > 0 ? forms.values().next().value! : null
      Promise.resolve().then(() => {
        if (!disposed)
          setApi(nextApi)
      })
    }
    update(hook.forms)
    const unsubscribe = hook.onChange(update)
    return () => {
      disposed = true
      unsubscribe()
    }
  }, [])

  if (!api)
    return null
  return <DevToolsPanel api={api} />
}
