// playground-vue/src/antd-vue/config/CardGroupForm.vue
<template>
  <div>
    <h2>卡片分组</h2>
    <p style="color: rgba(0,0,0,0.45); margin-bottom: 16px; font-size: 14px;">Card 多卡片分组布局</p>
    <PlaygroundForm :schema="schema" :initial-values="initialValues" />
  </div>
</template>

<script setup lang="ts">
import { setupAntdVue } from '@moluoxixi/ui-antd-vue'
import type { FormSchema } from '@moluoxixi/schema'
import PlaygroundForm from '../../components/PlaygroundForm.vue'

setupAntdVue()

const initialValues = { username: '', password: '', confirmPwd: '', realName: '', gender: undefined, birthday: '', email: '', phone: '', address: '' }

const schema: FormSchema = {
  form: { labelPosition: 'right', labelWidth: '120px' },
  layout: { type: 'groups', groups: [{ title: '账户信息', component: 'Card', fields: ['username', 'password', 'confirmPwd'] }, { title: '个人信息', component: 'Card', fields: ['realName', 'gender', 'birthday'] }, { title: '联系方式', component: 'Card', fields: ['email', 'phone', 'address'] }] },
  fields: {
    username: { type: 'string', label: '用户名', required: true, component: 'Input', wrapper: 'FormItem', rules: [{ minLength: 3, message: '至少 3 字符' }] },
    password: { type: 'string', label: '密码', required: true, component: 'Password', wrapper: 'FormItem', rules: [{ minLength: 8, message: '至少 8 字符' }] },
    confirmPwd: { type: 'string', label: '确认密码', required: true, component: 'Password', wrapper: 'FormItem', rules: [{ validator: (v: unknown, _r: unknown, ctx: any) => v !== ctx.getFieldValue('password') ? '密码不一致' : undefined, trigger: 'blur' }] },
    realName: { type: 'string', label: '真实姓名', required: true, component: 'Input', wrapper: 'FormItem' },
    gender: { type: 'string', label: '性别', component: 'RadioGroup', wrapper: 'FormItem', enum: [{ label: '男', value: 'male' }, { label: '女', value: 'female' }] },
    birthday: { type: 'string', label: '生日', component: 'DatePicker', wrapper: 'FormItem' },
    email: { type: 'string', label: '邮箱', required: true, component: 'Input', wrapper: 'FormItem', rules: [{ format: 'email', message: '无效邮箱' }] },
    phone: { type: 'string', label: '手机号', component: 'Input', wrapper: 'FormItem', rules: [{ format: 'phone', message: '无效手机号' }] },
    address: { type: 'string', label: '地址', component: 'Textarea', wrapper: 'FormItem' },
  },
}
</script>

// playground-react/src/antd/config/CardGroupForm.tsx
/**
 * 场景 24：卡片分组
 *
 * 覆盖：
 * - Card 组件包裹字段组
 * - 多卡片布局
 * - 卡片内独立验证提示
 * - 三种模式切换
 */
import React from 'react';
import { observer } from 'mobx-react-lite';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Typography } from 'antd';
import type { FormSchema } from '@moluoxixi/schema';
import { PlaygroundForm } from '../../components/PlaygroundForm';

const { Title, Paragraph } = Typography;

setupAntd();

/** 默认初始值 */
const INITIAL_VALUES: Record<string, unknown> = {
  username: '', password: '', confirmPwd: '', realName: '', gender: undefined, birthday: '',
  email: '', phone: '', address: '',
};

/** 表单 Schema */
const schema: FormSchema = {
  form: { labelPosition: 'right', labelWidth: '120px' },
  layout: {
    type: 'groups',
    groups: [
      { title: '账户信息', component: 'Card', fields: ['username', 'password', 'confirmPwd'] },
      { title: '个人信息', component: 'Card', fields: ['realName', 'gender', 'birthday'] },
      { title: '联系方式', component: 'Card', fields: ['email', 'phone', 'address'] },
    ],
  },
  fields: {
    username: { type: 'string', label: '用户名', required: true, component: 'Input', wrapper: 'FormItem', placeholder: '请输入用户名', rules: [{ minLength: 3, message: '至少 3 字符' }] },
    password: { type: 'string', label: '密码', required: true, component: 'Password', wrapper: 'FormItem', placeholder: '请输入密码', rules: [{ minLength: 8, message: '至少 8 字符' }] },
    confirmPwd: {
      type: 'string', label: '确认密码', required: true, component: 'Password', wrapper: 'FormItem', placeholder: '再次输入',
      rules: [{ validator: (v, _r, ctx) => { if (v !== ctx.getFieldValue('password')) return '密码不一致'; return undefined; }, trigger: 'blur' }],
    },
    realName: { type: 'string', label: '真实姓名', required: true, component: 'Input', wrapper: 'FormItem', placeholder: '请输入姓名' },
    gender: {
      type: 'string', label: '性别', component: 'RadioGroup', wrapper: 'FormItem',
      enum: [{ label: '男', value: 'male' }, { label: '女', value: 'female' }],
    },
    birthday: { type: 'string', label: '生日', component: 'DatePicker', wrapper: 'FormItem' },
    email: { type: 'string', label: '邮箱', required: true, component: 'Input', wrapper: 'FormItem', placeholder: '请输入邮箱', rules: [{ format: 'email', message: '无效邮箱' }] },
    phone: { type: 'string', label: '手机号', component: 'Input', wrapper: 'FormItem', placeholder: '请输入手机号', rules: [{ format: 'phone', message: '无效手机号' }] },
    address: { type: 'string', label: '地址', component: 'Textarea', wrapper: 'FormItem', placeholder: '请输入地址' },
  },
};

export const CardGroupForm = observer((): React.ReactElement => {
  return (
    <div>
      <Title level={3}>卡片分组</Title>
      <Paragraph type="secondary">Card 多卡片分组布局 / 卡片内独立验证</Paragraph>
      <PlaygroundForm schema={schema} initialValues={INITIAL_VALUES} />
    </div>
  );
});
