// playground-vue/src/element-plus/config/CrossFieldValidationForm.vue
<template>
  <div>
    <h2>跨字段验证</h2>
    <p style="color: #909399; margin-bottom: 16px; font-size: 14px;">密码一致性 / 日期范围 / 比例总和=100% / 数值区间 / 预算限制</p>
    <el-radio-group v-model="mode" size="small" style="margin-bottom: 16px">
      <el-radio-button v-for="opt in MODE_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</el-radio-button>
    </el-radio-group>
    <ConfigForm :key="mode" :schema="schema" :initial-values="savedValues" @values-change="(v: Record<string, unknown>) => savedValues = v" @submit="(v: Record<string, unknown>) => result = JSON.stringify(v, null, 2)" @submit-failed="(e: any[]) => result = '验证失败:\n' + e.map((x: any) => `[${x.path}] ${x.message}`).join('\n')">
      <template #default="{ form }"><el-space v-if="mode === 'editable'" style="margin-top: 16px"><el-button type="primary" native-type="submit">提交</el-button><el-button @click="form.reset()">重置</el-button></el-space></template>
    </ConfigForm>
    <el-alert v-if="result" :type="result.startsWith('验证失败') ? 'error' : 'success'" :description="result" show-icon style="margin-top: 16px" />
  </div>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { ConfigForm } from '@moluoxixi/vue'
import { setupElementPlus } from '@moluoxixi/ui-element-plus'
import type { FormSchema } from '@moluoxixi/schema'
import type { FieldPattern } from '@moluoxixi/shared'
setupElementPlus()
const MODE_OPTIONS = [{ label: '编辑态', value: 'editable' }, { label: '阅读态', value: 'readOnly' }, { label: '禁用态', value: 'disabled' }]
const mode = ref<FieldPattern>('editable')
const result = ref('')
const savedValues = ref<Record<string, unknown>>({ password: '', confirmPassword: '', startDate: '', endDate: '', ratioA: 40, ratioB: 30, ratioC: 30, minAge: 18, maxAge: 60, budget: 10000, expense: 0 })

const schema = computed<FormSchema>(() => ({
  form: { labelPosition: 'right', labelWidth: '150px', pattern: mode.value },
  fields: {
    password: { type: 'string', label: '密码', required: true, component: 'Password', wrapper: 'FormItem', rules: [{ minLength: 8, message: '至少 8 字符' }] },
    confirmPassword: { type: 'string', label: '确认密码', required: true, component: 'Password', wrapper: 'FormItem', rules: [{ validator: (v: unknown, _r: unknown, ctx: any) => { if (v && ctx.getFieldValue('password') && v !== ctx.getFieldValue('password')) return '密码不一致'; return undefined }, trigger: 'blur' }] },
    startDate: { type: 'string', label: '开始日期', required: true, component: 'DatePicker', wrapper: 'FormItem' },
    endDate: { type: 'string', label: '结束日期', required: true, component: 'DatePicker', wrapper: 'FormItem', rules: [{ validator: (v: unknown, _r: unknown, ctx: any) => { const s = ctx.getFieldValue('startDate') as string; if (s && v && String(v) < s) return '结束日期不能早于开始日期'; return undefined }, trigger: 'blur' }] },
    ratioA: { type: 'number', label: '项目 A（%）', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 40, componentProps: { min: 0, max: 100, style: { width: '100%' } }, description: 'A+B+C=100' },
    ratioB: { type: 'number', label: '项目 B（%）', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 30, componentProps: { min: 0, max: 100, style: { width: '100%' } } },
    ratioC: { type: 'number', label: '项目 C（%）', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 30, componentProps: { min: 0, max: 100, style: { width: '100%' } }, rules: [{ validator: (_v: unknown, _r: unknown, ctx: any) => { const t = ((ctx.getFieldValue('ratioA') as number) ?? 0) + ((ctx.getFieldValue('ratioB') as number) ?? 0) + ((ctx.getFieldValue('ratioC') as number) ?? 0); if (t !== 100) return `总和须为 100%，当前 ${t}%`; return undefined }, trigger: 'blur' }] },
    minAge: { type: 'number', label: '最小年龄', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 18, componentProps: { min: 0, max: 150, style: { width: '100%' } } },
    maxAge: { type: 'number', label: '最大年龄', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 60, componentProps: { min: 0, max: 150, style: { width: '100%' } }, rules: [{ validator: (v: unknown, _r: unknown, ctx: any) => { if (Number(v) <= (ctx.getFieldValue('minAge') as number)) return '须大于最小年龄'; return undefined }, trigger: 'blur' }] },
    budget: { type: 'number', label: '预算上限', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 10000, componentProps: { min: 0, style: { width: '100%' } } },
    expense: { type: 'number', label: '实际支出', required: true, component: 'InputNumber', wrapper: 'FormItem', defaultValue: 0, componentProps: { min: 0, style: { width: '100%' } }, rules: [{ validator: (v: unknown, _r: unknown, ctx: any) => { if (Number(v) > (ctx.getFieldValue('budget') as number)) return `支出不能超过预算`; return undefined }, trigger: 'blur' }] },
  },
}))
</script>

// playground-react/src/antd/config/CrossFieldValidationForm.tsx
/**
 * 场景 13：跨字段验证
 *
 * 覆盖：
 * - 密码一致性验证（password === confirmPassword）
 * - 日期范围验证（endDate >= startDate）
 * - 数值总和限制（分配比例之和 = 100%）
 * - 数值区间不重叠验证
 * - 三种模式切换
 */
import React, { useState, useMemo } from 'react';
import { observer } from 'mobx-react-lite';
import { ConfigForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Button, Space, Typography, Alert, Segmented, Divider } from 'antd';
import type { FormSchema } from '@moluoxixi/schema';
import type { FieldPattern } from '@moluoxixi/shared';

const { Title, Paragraph } = Typography;

setupAntd();

/** 模式选项 */
const MODE_OPTIONS = [
  { label: '编辑态', value: 'editable' },
  { label: '阅读态', value: 'readOnly' },
  { label: '禁用态', value: 'disabled' },
];

/**
 * 构建 Schema
 *
 * @param mode - 表单模式
 */
function buildSchema(mode: FieldPattern): FormSchema {
  return {
    form: { labelPosition: 'right', labelWidth: '150px', pattern: mode },
    fields: {
      /* ---- 场景 A：密码一致性 ---- */
      password: {
        type: 'string',
        label: '密码',
        required: true,
        component: 'Password',
        wrapper: 'FormItem',
        placeholder: '请输入密码',
        rules: [{ minLength: 8, message: '密码至少 8 个字符' }],
      },
      confirmPassword: {
        type: 'string',
        label: '确认密码',
        required: true,
        component: 'Password',
        wrapper: 'FormItem',
        placeholder: '请再次输入密码',
        rules: [
          {
            validator: (value, _rule, context) => {
              const pwd = context.getFieldValue('password');
              if (value && pwd && value !== pwd) {
                return '两次输入的密码不一致';
              }
              return undefined;
            },
            trigger: 'blur',
          },
        ],
      },

      /* ---- 场景 B：日期范围 ---- */
      startDate: {
        type: 'string',
        label: '开始日期',
        required: true,
        component: 'DatePicker',
        wrapper: 'FormItem',
      },
      endDate: {
        type: 'string',
        label: '结束日期',
        required: true,
        component: 'DatePicker',
        wrapper: 'FormItem',
        rules: [
          {
            validator: (value, _rule, context) => {
              const start = context.getFieldValue('startDate') as string;
              if (start && value && String(value) < start) {
                return '结束日期不能早于开始日期';
              }
              return undefined;
            },
            trigger: 'blur',
          },
          {
            level: 'warning',
            validator: (value, _rule, context) => {
              const start = context.getFieldValue('startDate') as string;
              if (start && value) {
                const diffMs = new Date(String(value)).getTime() - new Date(start).getTime();
                const diffDays = diffMs / (1000 * 60 * 60 * 24);
                if (diffDays > 365) return '日期跨度超过一年，请确认';
              }
              return undefined;
            },
          },
        ],
      },

      /* ---- 场景 C：比例总和 = 100% ---- */
      ratioA: {
        type: 'number',
        label: '项目 A 比例（%）',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 40,
        componentProps: { min: 0, max: 100, style: { width: '100%' } },
        description: 'A + B + C 必须等于 100',
      },
      ratioB: {
        type: 'number',
        label: '项目 B 比例（%）',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 30,
        componentProps: { min: 0, max: 100, style: { width: '100%' } },
      },
      ratioC: {
        type: 'number',
        label: '项目 C 比例（%）',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 30,
        componentProps: { min: 0, max: 100, style: { width: '100%' } },
        rules: [
          {
            validator: (_value, _rule, context) => {
              const a = (context.getFieldValue('ratioA') as number) ?? 0;
              const b = (context.getFieldValue('ratioB') as number) ?? 0;
              const c = (context.getFieldValue('ratioC') as number) ?? 0;
              const total = a + b + c;
              if (total !== 100) {
                return `三项比例之和必须等于 100%，当前为 ${total}%`;
              }
              return undefined;
            },
            trigger: 'blur',
          },
        ],
      },

      /* ---- 场景 D：数值区间不重叠 ---- */
      minAge: {
        type: 'number',
        label: '最小年龄',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 18,
        componentProps: { min: 0, max: 150, style: { width: '100%' } },
      },
      maxAge: {
        type: 'number',
        label: '最大年龄',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 60,
        componentProps: { min: 0, max: 150, style: { width: '100%' } },
        rules: [
          {
            validator: (value, _rule, context) => {
              const minVal = context.getFieldValue('minAge') as number;
              if (minVal !== undefined && value !== undefined && Number(value) <= minVal) {
                return '最大年龄必须大于最小年龄';
              }
              return undefined;
            },
            trigger: 'blur',
          },
        ],
      },

      /* ---- 场景 E：总金额不超过预算 ---- */
      budget: {
        type: 'number',
        label: '预算上限',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 10000,
        componentProps: { min: 0, style: { width: '100%' } },
      },
      expense: {
        type: 'number',
        label: '实际支出',
        required: true,
        component: 'InputNumber',
        wrapper: 'FormItem',
        defaultValue: 0,
        componentProps: { min: 0, style: { width: '100%' } },
        rules: [
          {
            validator: (value, _rule, context) => {
              const budgetVal = context.getFieldValue('budget') as number;
              if (budgetVal !== undefined && Number(value) > budgetVal) {
                return `实际支出（${value}）不能超过预算上限（${budgetVal}）`;
              }
              return undefined;
            },
            trigger: 'blur',
          },
          {
            level: 'warning',
            validator: (value, _rule, context) => {
              const budgetVal = (context.getFieldValue('budget') as number) ?? 0;
              if (budgetVal > 0 && Number(value) > budgetVal * 0.8) {
                return '支出已超过预算的 80%，请注意控制';
              }
              return undefined;
            },
          },
        ],
      },
    },
  };
}

/** 默认初始值 */
const INITIAL_VALUES: Record<string, unknown> = {
  password: '',
  confirmPassword: '',
  startDate: '',
  endDate: '',
  ratioA: 40,
  ratioB: 30,
  ratioC: 30,
  minAge: 18,
  maxAge: 60,
  budget: 10000,
  expense: 0,
};

/**
 * 跨字段验证示例
 */
export const CrossFieldValidationForm = observer((): React.ReactElement => {
  const [mode, setMode] = useState<FieldPattern>('editable');
  const [result, setResult] = useState('');
  const [savedValues, setSavedValues] = useState<Record<string, unknown>>({ ...INITIAL_VALUES });

  const schema = useMemo(() => buildSchema(mode), [mode]);

  return (
    <div>
      <Title level={3}>跨字段验证</Title>
      <Paragraph type="secondary">
        密码一致性 / 日期范围 / 比例总和 = 100% / 数值区间不重叠 / 预算限制
      </Paragraph>

      <Segmented
        value={mode}
        onChange={(val) => setMode(val as FieldPattern)}
        options={MODE_OPTIONS}
        style={{ marginBottom: 16 }}
      />

      <ConfigForm
        key={mode}
        schema={schema}
        initialValues={savedValues}
        onValuesChange={(values) => setSavedValues(values as Record<string, unknown>)}
        onSubmit={(values) => setResult(JSON.stringify(values, null, 2))}
        onSubmitFailed={(errors) =>
          setResult('验证失败:\n' + errors.map((e) => `[${e.path}] ${e.message}`).join('\n'))
        }
      >
        {mode === 'editable' && (
          <>
            <Divider />
            <Space>
              <Button type="primary" htmlType="submit">提交</Button>
              <Button htmlType="reset">重置</Button>
            </Space>
          </>
        )}
      </ConfigForm>

      {result && (
        <Alert
          style={{ marginTop: 16 }}
          type={result.startsWith('验证失败') ? 'error' : 'success'}
          message="提交结果"
          description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>}
        />
      )}
    </div>
  );
});
