// playground-vue/src/antd-vue/config/VisibilityLinkageForm.vue
<template>
  <div>
    <h2>显隐联动</h2>
    <p style="color: rgba(0,0,0,0.45); margin-bottom: 16px; font-size: 14px;">用户类型切换 / 开关控制多字段 / 嵌套显隐</p>
    <PlaygroundForm :schema="schema" :initial-values="initialValues" />
  </div>
</template>

<script setup lang="ts">
import { setupAntdVue } from '@moluoxixi/ui-antd-vue'
import type { FormSchema } from '@moluoxixi/schema'
import PlaygroundForm from '../../components/PlaygroundForm.vue'

setupAntdVue()

const initialValues = { userType: 'personal', realName: '', idCard: '', companyName: '', taxNumber: '', enableNotify: false, notifyEmail: '', notifyFrequency: undefined, hasAddress: false, city: '', hasDetailAddress: false, detailAddress: '' }

const schema: FormSchema = {
  form: { labelPosition: 'right', labelWidth: '140px' },
  fields: {
    userType: { type: 'string', label: '用户类型', required: true, component: 'RadioGroup', wrapper: 'FormItem', defaultValue: 'personal', enum: [{ label: '个人', value: 'personal' }, { label: '企业', value: 'business' }] },
    realName: { type: 'string', label: '真实姓名', required: true, component: 'Input', wrapper: 'FormItem', placeholder: '请输入', excludeWhenHidden: true, reactions: [{ watch: 'userType', when: (v: unknown[]) => v[0] === 'personal', fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    idCard: { type: 'string', label: '身份证号', component: 'Input', wrapper: 'FormItem', placeholder: '18 位', excludeWhenHidden: true, rules: [{ pattern: /^\d{17}[\dXx]$/, message: '无效身份证' }], reactions: [{ watch: 'userType', when: (v: unknown[]) => v[0] === 'personal', fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    companyName: { type: 'string', label: '公司名称', required: true, component: 'Input', wrapper: 'FormItem', placeholder: '请输入', visible: false, excludeWhenHidden: true, reactions: [{ watch: 'userType', when: (v: unknown[]) => v[0] === 'business', fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    taxNumber: { type: 'string', label: '税号', component: 'Input', wrapper: 'FormItem', placeholder: '请输入', visible: false, excludeWhenHidden: true, reactions: [{ watch: 'userType', when: (v: unknown[]) => v[0] === 'business', fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    enableNotify: { type: 'boolean', label: '开启通知', component: 'Switch', wrapper: 'FormItem', defaultValue: false },
    notifyEmail: { type: 'string', label: '通知邮箱', component: 'Input', wrapper: 'FormItem', placeholder: '邮箱', visible: false, excludeWhenHidden: true, rules: [{ format: 'email', message: '无效邮箱' }], reactions: [{ watch: 'enableNotify', when: (v: unknown[]) => v[0] === true, fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    notifyFrequency: { type: 'string', label: '通知频率', component: 'Select', wrapper: 'FormItem', visible: false, excludeWhenHidden: true, enum: [{ label: '实时', value: 'realtime' }, { label: '每日', value: 'daily' }, { label: '每周', value: 'weekly' }], reactions: [{ watch: 'enableNotify', when: (v: unknown[]) => v[0] === true, fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    hasAddress: { type: 'boolean', label: '填写地址', component: 'Switch', wrapper: 'FormItem', defaultValue: false },
    city: { type: 'string', label: '城市', component: 'Input', wrapper: 'FormItem', visible: false, excludeWhenHidden: true, reactions: [{ watch: 'hasAddress', when: (v: unknown[]) => v[0] === true, fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    hasDetailAddress: { type: 'boolean', label: '填写详细地址', component: 'Switch', wrapper: 'FormItem', visible: false, defaultValue: false, reactions: [{ watch: 'hasAddress', when: (v: unknown[]) => v[0] === true, fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
    detailAddress: { type: 'string', label: '详细地址', component: 'Textarea', wrapper: 'FormItem', visible: false, excludeWhenHidden: true, reactions: [{ watch: ['hasAddress', 'hasDetailAddress'], when: (v: unknown[]) => v[0] === true && v[1] === true, fulfill: { state: { visible: true } }, otherwise: { state: { visible: false } } }] },
  },
}
</script>

// playground-react/src/antd/config/VisibilityLinkageForm.tsx
/**
 * 场景 5：显隐联动
 *
 * 覆盖：
 * - 单字段控制：用户类型切换显示不同字段组
 * - 多字段控制：开关控制多个字段显隐
 * - 嵌套显隐：A 控制 B 显示，B 控制 C 显示
 * - excludeWhenHidden 隐藏时排除提交数据
 * - 三种模式切换
 */
import React from 'react';
import { observer } from 'mobx-react-lite';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Typography } from 'antd';
import type { FormSchema } from '@moluoxixi/schema';
import { PlaygroundForm } from '../../components/PlaygroundForm';

const { Title, Paragraph } = Typography;

setupAntd();

/** 默认初始值 */
const INITIAL_VALUES: Record<string, unknown> = {
  userType: 'personal',
  realName: '',
  idCard: '',
  companyName: '',
  taxNumber: '',
  enableNotify: false,
  notifyEmail: '',
  notifyFrequency: undefined,
  hasAddress: false,
  city: '',
  hasDetailAddress: false,
  detailAddress: '',
};

/** 表单 Schema */
const schema: FormSchema = {
  form: { labelPosition: 'right', labelWidth: '140px' },
  fields: {
    /* ---- 场景 A：类型切换显隐 ---- */
    userType: {
      type: 'string',
      label: '用户类型',
      required: true,
      component: 'RadioGroup',
      wrapper: 'FormItem',
      defaultValue: 'personal',
      enum: [
        { label: '个人', value: 'personal' },
        { label: '企业', value: 'business' },
      ],
    },

    /* 个人字段 */
    realName: {
      type: 'string',
      label: '真实姓名',
      required: true,
      component: 'Input',
      wrapper: 'FormItem',
      placeholder: '请输入真实姓名',
      excludeWhenHidden: true,
      reactions: [
        {
          watch: 'userType',
          when: (v) => v[0] === 'personal',
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },
    idCard: {
      type: 'string',
      label: '身份证号',
      component: 'Input',
      wrapper: 'FormItem',
      placeholder: '18 位身份证号',
      excludeWhenHidden: true,
      rules: [{ pattern: /^\d{17}[\dXx]$/, message: '请输入有效身份证号' }],
      reactions: [
        {
          watch: 'userType',
          when: (v) => v[0] === 'personal',
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },

    /* 企业字段 */
    companyName: {
      type: 'string',
      label: '公司名称',
      required: true,
      component: 'Input',
      wrapper: 'FormItem',
      placeholder: '请输入公司全称',
      visible: false,
      excludeWhenHidden: true,
      reactions: [
        {
          watch: 'userType',
          when: (v) => v[0] === 'business',
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },
    taxNumber: {
      type: 'string',
      label: '税号',
      component: 'Input',
      wrapper: 'FormItem',
      placeholder: '纳税人识别号',
      visible: false,
      excludeWhenHidden: true,
      reactions: [
        {
          watch: 'userType',
          when: (v) => v[0] === 'business',
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },

    /* ---- 场景 B：开关控制多字段 ---- */
    enableNotify: {
      type: 'boolean',
      label: '开启通知',
      component: 'Switch',
      wrapper: 'FormItem',
      defaultValue: false,
    },
    notifyEmail: {
      type: 'string',
      label: '通知邮箱',
      component: 'Input',
      wrapper: 'FormItem',
      placeholder: '通知邮箱',
      visible: false,
      excludeWhenHidden: true,
      rules: [{ format: 'email', message: '请输入有效邮箱' }],
      reactions: [
        {
          watch: 'enableNotify',
          when: (v) => v[0] === true,
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },
    notifyFrequency: {
      type: 'string',
      label: '通知频率',
      component: 'Select',
      wrapper: 'FormItem',
      visible: false,
      excludeWhenHidden: true,
      enum: [
        { label: '实时', value: 'realtime' },
        { label: '每日', value: 'daily' },
        { label: '每周', value: 'weekly' },
      ],
      reactions: [
        {
          watch: 'enableNotify',
          when: (v) => v[0] === true,
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },

    /* ---- 场景 C：嵌套显隐（A→B→C） ---- */
    hasAddress: {
      type: 'boolean',
      label: '填写地址',
      component: 'Switch',
      wrapper: 'FormItem',
      defaultValue: false,
    },
    city: {
      type: 'string',
      label: '城市',
      component: 'Input',
      wrapper: 'FormItem',
      placeholder: '请输入城市',
      visible: false,
      excludeWhenHidden: true,
      reactions: [
        {
          watch: 'hasAddress',
          when: (v) => v[0] === true,
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },
    hasDetailAddress: {
      type: 'boolean',
      label: '填写详细地址',
      component: 'Switch',
      wrapper: 'FormItem',
      visible: false,
      defaultValue: false,
      reactions: [
        {
          watch: 'hasAddress',
          when: (v) => v[0] === true,
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },
    detailAddress: {
      type: 'string',
      label: '详细地址',
      component: 'Textarea',
      wrapper: 'FormItem',
      placeholder: '街道门牌号',
      visible: false,
      excludeWhenHidden: true,
      reactions: [
        {
          watch: ['hasAddress', 'hasDetailAddress'],
          when: (v) => v[0] === true && v[1] === true,
          fulfill: { state: { visible: true } },
          otherwise: { state: { visible: false } },
        },
      ],
    },
  },
};

/**
 * 显隐联动示例
 */
export const VisibilityLinkageForm = observer((): React.ReactElement => {
  return (
    <div>
      <Title level={3}>显隐联动</Title>
      <Paragraph type="secondary">
        用户类型切换 / 开关控制多字段 / 嵌套显隐（A→B→C） / 隐藏字段排除提交
      </Paragraph>
      <PlaygroundForm schema={schema} initialValues={INITIAL_VALUES} />
    </div>
  );
});
