// playground-vue/src/antd-vue/field/CustomFieldForm.vue
<script setup lang="ts">
/**
 * Ant Design Vue Field 组件模式 - 自定义渲染
 *
 * 演示：使用 FormField + v-slot 自定义渲染 Ant Design Vue 组件
 * - v-slot 获取 field 实例完全控制渲染（a-input / a-input-password）
 * - 跨字段验证（密码确认）
 * - 自定义布局和交互
 */
import { ref } from 'vue';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/vue';
import { setupAntdVue } from '@moluoxixi/ui-antd-vue';

setupAntdVue();

const form = useCreateForm({
  initialValues: { username: '', password: '', confirmPassword: '', role: '', bio: '', agree: false },
});

/* 创建字段 */
form.createField({
  name: 'username', label: '用户名', required: true,
  rules: [
    { minLength: 3, message: '用户名至少 3 个字符' },
    { maxLength: 20, message: '用户名最多 20 个字符' },
    { pattern: /^[a-zA-Z0-9_]+$/, message: '用户名只能包含字母、数字和下划线' },
  ],
});

form.createField({
  name: 'password', label: '密码', required: true,
  rules: [
    { minLength: 6, message: '密码至少 6 位' },
    {
      validator: (value) => {
        const str = String(value);
        if (!/[A-Z]/.test(str)) return '密码须包含至少一个大写字母';
        if (!/[0-9]/.test(str)) return '密码须包含至少一个数字';
      },
    },
  ],
});

/* 跨字段验证 - 密码确认 */
form.createField({
  name: 'confirmPassword', label: '确认密码', required: true,
  rules: [{
    validator: (value, _rule, context) => {
      const password = context.getFieldValue('password');
      if (value !== password) return '两次密码不一致';
    },
  }],
});

form.createField({
  name: 'role', label: '角色', required: true,
  dataSource: [
    { label: '前端工程师', value: 'frontend' },
    { label: '后端工程师', value: 'backend' },
    { label: '全栈工程师', value: 'fullstack' },
    { label: '设计师', value: 'designer' },
  ],
});

form.createField({ name: 'bio', label: '个人简介' });
form.createField({
  name: 'agree', label: '同意条款',
  rules: [{ validator: (value) => { if (!value) return '请阅读并同意用户协议'; } }],
});

const submitResult = ref('');

async function handleSubmit(): Promise<void> {
  const result = await form.submit();
  if (result.errors.length > 0) {
    submitResult.value = '验证失败:\n' + result.errors.map((e) => `  ${e.path}: ${e.message}`).join('\n');
  } else {
    submitResult.value = JSON.stringify(result.values, null, 2);
  }
}
</script>

<template>
  <div>
    <h2 style="margin-bottom: 8px;">Ant Design Vue Field 组件 - 自定义渲染</h2>
    <p style="color: rgba(0,0,0,0.45); margin-bottom: 20px; font-size: 14px;">
      v-slot 自定义渲染（a-input / a-input-password）/ 跨字段验证（密码确认）
    </p>

    <FormProvider :form="form">
      <form @submit.prevent="handleSubmit">
        <a-card style="margin-bottom: 20px;">
          <template #title>账号信息</template>

          <FormField name="username" v-slot="{ field }">
            <a-form-item :label="field.label" required :validate-status="field.errors.length > 0 ? 'error' : ''" :help="field.errors[0]?.message">
              <a-input :value="(field.value as string)" @update:value="field.setValue($event)" @focus="field.focus()" @blur="field.blur(); field.validate('blur')" placeholder="请输入用户名" />
            </a-form-item>
          </FormField>

          <FormField name="password" v-slot="{ field }">
            <a-form-item :label="field.label" required :validate-status="field.errors.length > 0 ? 'error' : ''" :help="field.errors[0]?.message">
              <a-input-password :value="(field.value as string)" @update:value="field.setValue($event)" @focus="field.focus()" @blur="field.blur(); field.validate('blur')" placeholder="请输入密码（含大写字母+数字）" />
            </a-form-item>
          </FormField>

          <FormField name="confirmPassword" v-slot="{ field }">
            <a-form-item :label="field.label" required :validate-status="field.errors.length > 0 ? 'error' : ''" :help="field.errors[0]?.message">
              <a-input-password :value="(field.value as string)" @update:value="field.setValue($event)" @focus="field.focus()" @blur="field.blur(); field.validate('blur')" placeholder="请再次输入密码" />
            </a-form-item>
          </FormField>
        </a-card>

        <a-card style="margin-bottom: 20px;">
          <template #title>个人信息</template>

          <FormField name="role" v-slot="{ field }">
            <a-form-item :label="field.label" required :validate-status="field.errors.length > 0 ? 'error' : ''" :help="field.errors[0]?.message">
              <a-select :value="(field.value as string) || undefined" @update:value="field.setValue($event)" placeholder="请选择角色" style="width: 100%;"
                :options="field.dataSource.map((item) => ({ label: item.label, value: item.value }))" />
            </a-form-item>
          </FormField>

          <FormField name="bio" v-slot="{ field }">
            <a-form-item :label="field.label">
              <a-textarea :value="(field.value as string)" @update:value="field.setValue($event)" :rows="3" placeholder="简单介绍一下自己..." />
            </a-form-item>
          </FormField>
        </a-card>

        <!-- 协议确认 -->
        <FormField name="agree" v-slot="{ field }">
          <div style="margin-bottom: 20px;">
            <a-checkbox :checked="!!field.value" @update:checked="field.setValue($event)">
              我已阅读并同意《用户服务协议》和《隐私政策》
            </a-checkbox>
            <div v-if="field.errors.length > 0" style="color: #ff4d4f; font-size: 12px; margin-top: 4px; margin-left: 24px;">
              {{ field.errors[0].message }}
            </div>
          </div>
        </FormField>

        <a-button type="primary" html-type="submit">注册</a-button>
      </form>
    </FormProvider>

    <a-card v-if="submitResult" style="margin-top: 20px;">
      <template #title><strong>结果</strong></template>
      <pre style="margin: 0; white-space: pre-wrap; font-size: 13px;">{{ submitResult }}</pre>
    </a-card>
  </div>
</template>

// playground-react/src/antd/field/CustomFieldForm.tsx
/**
 * 自定义组件 - antd 版
 *
 * 覆盖场景：
 * - render prop 自定义渲染（使用 antd Input / Password / Checkbox）
 * - 跨字段验证（密码确认）
 * - 密码强度指示器
 * - 自定义协议勾选
 */
import React, { useState } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import {
  Button, Typography, Alert, Input, Checkbox, Form, Progress, Space,
} from 'antd';
import { UserOutlined, LockOutlined, MailOutlined, PhoneOutlined } from '@ant-design/icons';
import type { FieldInstance } from '@moluoxixi/core';

const { Title, Paragraph, Text } = Typography;

setupAntd();

/** 密码强度等级 */
const PASSWORD_STRENGTH_LEVELS = [
  { label: '弱', color: '#ff4d4f', percent: 25 },
  { label: '中', color: '#faad14', percent: 50 },
  { label: '强', color: '#52c41a', percent: 75 },
  { label: '很强', color: '#1677ff', percent: 100 },
];

/** 计算密码强度 */
function getPasswordStrength(pwd: string): number {
  if (!pwd) return 0;
  let strength = 0;
  if (pwd.length >= 8) strength++;
  if (/[a-z]/.test(pwd) && /[A-Z]/.test(pwd)) strength++;
  if (/\d/.test(pwd)) strength++;
  if (/[^a-zA-Z0-9]/.test(pwd)) strength++;
  return Math.min(strength, 4);
}

/**
 * 自定义组件示例
 *
 * 使用 FormField + render prop 实现注册表单，包含密码强度指示器和跨字段验证。
 */
export const CustomFieldForm = observer(() => {
  const form = useCreateForm({
    initialValues: {
      username: '',
      email: '',
      phone: '',
      password: '',
      confirmPassword: '',
      agree: false,
    },
  });

  /* 创建字段 */
  React.useEffect(() => {
    form.createField({
      name: 'username',
      label: '用户名',
      required: true,
      rules: [
        { minLength: 3, message: '用户名至少 3 个字符' },
        { maxLength: 20, message: '用户名最多 20 个字符' },
        { pattern: /^[a-zA-Z0-9_]+$/, message: '只能包含字母、数字和下划线' },
      ],
    });
    form.createField({
      name: 'email',
      label: '邮箱',
      required: true,
      rules: [{ format: 'email', message: '请输入有效的邮箱' }],
    });
    form.createField({
      name: 'phone',
      label: '手机号',
      rules: [{ format: 'phone', message: '请输入有效的手机号' }],
    });
    form.createField({
      name: 'password',
      label: '密码',
      required: true,
      rules: [
        { minLength: 8, message: '密码至少 8 个字符' },
        {
          pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/,
          message: '需包含大小写字母和数字',
        },
      ],
    });
    form.createField({
      name: 'confirmPassword',
      label: '确认密码',
      required: true,
      rules: [
        {
          validator: (value, _rule, context) => {
            const pwd = context.getFieldValue('password');
            if (value !== pwd) return '两次密码不一致';
          },
        },
      ],
    });
    form.createField({
      name: 'agree',
      label: '同意条款',
      rules: [
        {
          validator: (value) => {
            if (!value) return '请阅读并同意用户协议';
          },
        },
      ],
    });
  }, []);

  const [result, setResult] = useState('');

  /** 提交 */
  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    const res = await form.submit();
    if (res.errors.length > 0) {
      setResult('验证失败: ' + res.errors.map((err) => err.message).join(', '));
    } else {
      setResult(JSON.stringify(res.values, null, 2));
    }
  };

  return (
    <div>
      <Title level={3}>自定义组件 - antd 版</Title>
      <Paragraph type="secondary">
        render prop 自定义渲染 / 跨字段验证（密码确认）/ 密码强度 / 自定义 Checkbox
      </Paragraph>

      <div style={{ maxWidth: 480 }}>
        <FormProvider form={form}>
          <form onSubmit={handleSubmit} noValidate>
            {/* 用户名 */}
            <FormField name="username">
              {(field: FieldInstance) => (
                <Form.Item
                  label={field.label}
                  required={field.required}
                  validateStatus={field.errors.length > 0 ? 'error' : undefined}
                  help={field.errors[0]?.message}
                >
                  <Input
                    prefix={<UserOutlined />}
                    value={(field.value as string) ?? ''}
                    onChange={(e) => field.setValue(e.target.value)}
                    onFocus={() => field.focus()}
                    onBlur={() => { field.blur(); field.validate('blur').catch(() => {}); }}
                    placeholder="请输入用户名"
                  />
                </Form.Item>
              )}
            </FormField>

            {/* 邮箱 */}
            <FormField name="email">
              {(field: FieldInstance) => (
                <Form.Item
                  label={field.label}
                  required={field.required}
                  validateStatus={field.errors.length > 0 ? 'error' : undefined}
                  help={field.errors[0]?.message}
                >
                  <Input
                    prefix={<MailOutlined />}
                    value={(field.value as string) ?? ''}
                    onChange={(e) => field.setValue(e.target.value)}
                    onBlur={() => { field.blur(); field.validate('blur').catch(() => {}); }}
                    placeholder="请输入邮箱"
                  />
                </Form.Item>
              )}
            </FormField>

            {/* 手机号 */}
            <FormField name="phone">
              {(field: FieldInstance) => (
                <Form.Item
                  label={field.label}
                  validateStatus={field.errors.length > 0 ? 'error' : undefined}
                  help={field.errors[0]?.message}
                >
                  <Input
                    prefix={<PhoneOutlined />}
                    value={(field.value as string) ?? ''}
                    onChange={(e) => field.setValue(e.target.value)}
                    onBlur={() => { field.blur(); field.validate('blur').catch(() => {}); }}
                    placeholder="请输入手机号（选填）"
                  />
                </Form.Item>
              )}
            </FormField>

            {/* 密码 + 强度指示 */}
            <FormField name="password">
              {(field: FieldInstance) => {
                const strength = getPasswordStrength((field.value as string) ?? '');
                const level = strength > 0 ? PASSWORD_STRENGTH_LEVELS[strength - 1] : null;
                return (
                  <Form.Item
                    label={field.label}
                    required={field.required}
                    validateStatus={field.errors.length > 0 ? 'error' : undefined}
                    help={field.errors[0]?.message}
                  >
                    <Input.Password
                      prefix={<LockOutlined />}
                      value={(field.value as string) ?? ''}
                      onChange={(e) => field.setValue(e.target.value)}
                      onBlur={() => { field.blur(); field.validate('blur').catch(() => {}); }}
                      placeholder="请输入密码"
                    />
                    {(field.value as string)?.length > 0 && level && (
                      <div style={{ marginTop: 4 }}>
                        <Progress
                          percent={level.percent}
                          strokeColor={level.color}
                          showInfo={false}
                          size="small"
                        />
                        <Text style={{ fontSize: 12, color: level.color }}>密码强度：{level.label}</Text>
                      </div>
                    )}
                  </Form.Item>
                );
              }}
            </FormField>

            {/* 确认密码 */}
            <FormField name="confirmPassword">
              {(field: FieldInstance) => (
                <Form.Item
                  label={field.label}
                  required={field.required}
                  validateStatus={field.errors.length > 0 ? 'error' : undefined}
                  help={field.errors[0]?.message}
                >
                  <Input.Password
                    prefix={<LockOutlined />}
                    value={(field.value as string) ?? ''}
                    onChange={(e) => field.setValue(e.target.value)}
                    onBlur={() => { field.blur(); field.validate('blur').catch(() => {}); }}
                    placeholder="请再次输入密码"
                  />
                </Form.Item>
              )}
            </FormField>

            {/* 同意协议 */}
            <FormField name="agree">
              {(field: FieldInstance) => (
                <Form.Item
                  validateStatus={field.errors.length > 0 ? 'error' : undefined}
                  help={field.errors[0]?.message}
                >
                  <Checkbox
                    checked={!!field.value}
                    onChange={(e) => field.setValue(e.target.checked)}
                  >
                    我已阅读并同意 <a href="#" onClick={(e) => e.preventDefault()}>《用户协议》</a> 和 <a href="#" onClick={(e) => e.preventDefault()}>《隐私政策》</a>
                  </Checkbox>
                </Form.Item>
              )}
            </FormField>

            <Button type="primary" htmlType="submit" block size="large">
              注册
            </Button>
          </form>
        </FormProvider>
      </div>

      {result && (
        <Alert
          style={{ marginTop: 16 }}
          type={result.startsWith('验证失败') ? 'error' : 'success'}
          message="结果"
          description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>}
        />
      )}
    </div>
  );
});
