// playground-vue/src/element-plus/field/DataTransformForm.vue
<template>
  <div>
    <h2>数据转换</h2>
    <p style="color: #909399; margin-bottom: 16px; font-size: 14px;">format / parse / transform / submitPath</p>
    <el-radio-group v-model="mode" size="small" style="margin-bottom: 16px">
      <el-radio-button v-for="opt in MODE_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</el-radio-button>
    </el-radio-group>
    <FormProvider :form="form">
      <form @submit.prevent="handleSubmit" novalidate>
        <FormField v-for="name in FIELDS" :key="name" v-slot="{ field }" :name="name"><el-form-item :label="field.label" :help="field.description"><el-space><el-input :model-value="String(field.value ?? '')" @update:model-value="field.setValue($event)" :disabled="mode === 'disabled'" style="width: 300px" /><el-tag type="primary">原始: {{ JSON.stringify(field.value) }}</el-tag></el-space></el-form-item></FormField>
        <el-button v-if="mode === 'editable'" type="primary" native-type="submit" style="margin-top: 8px">提交（查看转换结果）</el-button>
      </form>
    </FormProvider>
    <el-alert v-if="rawValues" type="info" title="表单原始值" style="margin-top: 16px" :description="rawValues" show-icon />
    <el-alert v-if="result" :type="result.startsWith('验证失败') ? 'error' : 'success'" title="提交转换后" style="margin-top: 8px" :description="result" show-icon />
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/vue'
import { setupElementPlus } from '@moluoxixi/ui-element-plus'
import { ElButton, ElSpace, ElAlert, ElRadioGroup, ElRadioButton, ElInput, ElFormItem, ElTag } from 'element-plus'
import type { FieldPattern } from '@moluoxixi/shared'
setupElementPlus()
const MODE_OPTIONS = [{ label: '编辑态', value: 'editable' }, { label: '阅读态', value: 'readOnly' }, { label: '禁用态', value: 'disabled' }]
const mode = ref<FieldPattern>('editable')
const result = ref('')
const rawValues = ref('')
const FIELDS = ['priceCent', 'phoneRaw', 'fullName', 'tags']
const form = useCreateForm({ initialValues: { priceCent: 9990, phoneRaw: '13800138000', fullName: '张三', tags: 'react,vue,typescript' } })
onMounted(() => {
  form.createField({ name: 'priceCent', label: '价格（分→元）', description: 'format: 分转元, parse: 元转分', format: (v: unknown) => v ? (Number(v) / 100).toFixed(2) : '', parse: (v: unknown) => Math.round(Number(v) * 100) })
  form.createField({ name: 'phoneRaw', label: '手机号（脱敏）', format: (v: unknown) => { const s = String(v ?? ''); return s.length === 11 ? `${s.slice(0, 3)}****${s.slice(7)}` : s } })
  form.createField({ name: 'fullName', label: '姓名' })
  form.createField({ name: 'tags', label: '标签（逗号分隔）', description: '提交时转为数组', transform: (v: unknown) => String(v ?? '').split(',').map(s => s.trim()).filter(Boolean) })
})
async function handleSubmit(): Promise<void> { rawValues.value = JSON.stringify(form.values, null, 2); const res = await form.submit(); result.value = res.errors.length > 0 ? '验证失败: ' + res.errors.map(e => e.message).join(', ') : JSON.stringify(res.values, null, 2) }
</script>

// playground-react/src/antd/field/DataTransformForm.tsx
/**
 * 场景 40：数据转换
 *
 * 覆盖：
 * - 提交前转换（transform）
 * - 显示时格式化（format）
 * - 输入时解析（parse）
 * - submitPath 路径映射
 * - 三种模式切换
 */
import React, { useState, useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Button, Typography, Alert, Segmented, Form, Input, InputNumber, Space, Tag } from 'antd';
import type { FieldInstance } from '@moluoxixi/core';
import type { FieldPattern } from '@moluoxixi/shared';

const { Title, Paragraph, Text } = Typography;

setupAntd();

const MODE_OPTIONS = [
  { label: '编辑态', value: 'editable' },
  { label: '阅读态', value: 'readOnly' },
  { label: '禁用态', value: 'disabled' },
];

export const DataTransformForm = observer((): React.ReactElement => {
  const [mode, setMode] = useState<FieldPattern>('editable');
  const [result, setResult] = useState('');
  const [rawValues, setRawValues] = useState('');

  const form = useCreateForm({
    initialValues: {
      priceCent: 9990,
      phoneRaw: '13800138000',
      fullName: '张三',
      tags: 'react,vue,typescript',
    },
  });

  useEffect(() => {
    form.createField({
      name: 'priceCent',
      label: '价格（分→元）',
      required: true,
      format: (v: unknown) => v ? (Number(v) / 100).toFixed(2) : '',
      parse: (v: unknown) => Math.round(Number(v) * 100),
      transform: (v: unknown) => Number(v),
    });
    form.createField({
      name: 'phoneRaw',
      label: '手机号（脱敏）',
      format: (v: unknown) => {
        const s = String(v ?? '');
        return s.length === 11 ? `${s.slice(0, 3)}****${s.slice(7)}` : s;
      },
      parse: (v: unknown) => String(v).replace(/\D/g, ''),
    });
    form.createField({ name: 'fullName', label: '姓名', required: true });
    form.createField({
      name: 'tags',
      label: '标签（逗号分隔）',
      description: '提交时转为数组',
      transform: (v: unknown) => String(v ?? '').split(',').map((s: string) => s.trim()).filter(Boolean),
    });
  }, []);

  const switchMode = (p: FieldPattern): void => {
    setMode(p);
    ['priceCent', 'phoneRaw', 'fullName', 'tags'].forEach((n) => { const f = form.getField(n); if (f) f.pattern = p; });
  };

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    setRawValues(JSON.stringify(form.values, null, 2));
    const res = await form.submit();
    if (res.errors.length > 0) { setResult('验证失败: ' + res.errors.map((err) => err.message).join(', ')); }
    else { setResult(JSON.stringify(res.values, null, 2)); }
  };

  return (
    <div>
      <Title level={3}>数据转换</Title>
      <Paragraph type="secondary">format（显示格式化） / parse（输入解析） / transform（提交转换）</Paragraph>
      <Segmented value={mode} onChange={(v) => switchMode(v as FieldPattern)} options={MODE_OPTIONS} style={{ marginBottom: 16 }} />

      <FormProvider form={form}>
        <form onSubmit={handleSubmit} noValidate>
          {['priceCent', 'phoneRaw', 'fullName', 'tags'].map((name) => (
            <FormField key={name} name={name}>
              {(field: FieldInstance) => (
                <Form.Item label={field.label} required={field.required} help={field.description}>
                  <Space>
                    <Input
                      value={String(field.value ?? '')}
                      onChange={(e) => field.setValue(e.target.value)}
                      disabled={mode === 'disabled'}
                      readOnly={mode === 'readOnly'}
                      style={{ width: 300 }}
                    />
                    <Tag color="blue">原始值: {JSON.stringify(field.value)}</Tag>
                  </Space>
                </Form.Item>
              )}
            </FormField>
          ))}

          {mode === 'editable' && <Button type="primary" htmlType="submit" style={{ marginTop: 8 }}>提交（查看转换结果）</Button>}
        </form>
      </FormProvider>

      {rawValues && (
        <Alert style={{ marginTop: 16 }} type="info" message="表单原始值" description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{rawValues}</pre>} />
      )}
      {result && (
        <Alert style={{ marginTop: 8 }} type={result.startsWith('验证失败') ? 'error' : 'success'} message="提交转换后的值" description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>} />
      )}
    </div>
  );
});
