// playground-vue/src/antd-vue/field/SignaturePadForm.vue
<template>
  <div>
    <h2>手写签名板</h2>
    <p style="color: rgba(0,0,0,0.45); margin-bottom: 16px; font-size: 14px;">Canvas 手写签名 / Base64 数据同步</p>
    <ASegmented v-model:value="mode" :options="MODE_OPTIONS" style="margin-bottom: 16px" />
    <FormProvider :form="form">
      <form @submit.prevent="handleSubmit" novalidate>
        <FormField v-slot="{ field }" name="signerName"><AFormItem :label="field.label" :required="field.required"><AInput :value="(field.value as string) ?? ''" @update:value="field.setValue($event)" :disabled="mode === 'disabled'" style="width: 300px" /></AFormItem></FormField>
        <AFormItem label="手写签名">
          <div v-if="mode === 'readOnly'">
            <img v-if="signatureData" :src="signatureData" alt="签名" style="border: 1px solid #d9d9d9; border-radius: 8px; max-width: 500px" />
            <span v-else style="color: #999">暂无签名</span>
          </div>
          <div v-else>
            <canvas ref="canvasRef" width="500" height="200" @mousedown="startDraw" @mousemove="drawing" @mouseup="endDraw" @mouseleave="endDraw" :style="{ border: '1px solid #d9d9d9', borderRadius: '8px', cursor: mode === 'disabled' ? 'not-allowed' : 'crosshair', background: mode === 'disabled' ? '#f5f5f5' : '#fff', display: 'block' }" />
            <AButton v-if="mode === 'editable'" size="small" style="margin-top: 8px" @click="clearCanvas">清空签名</AButton>
          </div>
        </AFormItem>
        <ASpace v-if="mode === 'editable'"><AButton type="primary" html-type="submit">提交</AButton><AButton @click="form.reset()">重置</AButton></ASpace>
      </form>
    </FormProvider>
    <AAlert v-if="result" :type="result.startsWith('验证失败') ? 'error' : 'success'" message="提交结果" style="margin-top: 16px"><template #description><pre style="margin: 0; white-space: pre-wrap">{{ result }}</pre></template></AAlert>
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/vue'
import { setupAntdVue } from '@moluoxixi/ui-antd-vue'
import { Button as AButton, Space as ASpace, Alert as AAlert, Segmented as ASegmented, Input as AInput, FormItem as AFormItem } from 'ant-design-vue'
import type { FieldPattern } from '@moluoxixi/shared'
setupAntdVue()
const MODE_OPTIONS = [{ label: '编辑态', value: 'editable' }, { label: '阅读态', value: 'readOnly' }, { label: '禁用态', value: 'disabled' }]
const mode = ref<FieldPattern>('editable')
const result = ref('')
const signatureData = ref('')
const canvasRef = ref<HTMLCanvasElement | null>(null)
let isDrawing = false
const form = useCreateForm({ initialValues: { signerName: '', signatureData: '' } })
watch(mode, (v) => { form.pattern = v })
onMounted(() => { form.createField({ name: 'signerName', label: '签名人', required: true }); form.createField({ name: 'signatureData', label: '签名' }) })
function getCtx(): CanvasRenderingContext2D | null { return canvasRef.value?.getContext('2d') ?? null }
function getPos(e: MouseEvent): { x: number; y: number } { const r = canvasRef.value!.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top } }
function startDraw(e: MouseEvent): void { if (mode.value === 'disabled') return; isDrawing = true; const ctx = getCtx(); if (!ctx) return; const p = getPos(e); ctx.beginPath(); ctx.moveTo(p.x, p.y) }
function drawing(e: MouseEvent): void { if (!isDrawing || mode.value === 'disabled') return; const ctx = getCtx(); if (!ctx) return; const p = getPos(e); ctx.lineWidth = 2; ctx.lineCap = 'round'; ctx.strokeStyle = '#333'; ctx.lineTo(p.x, p.y); ctx.stroke() }
function endDraw(): void { if (!isDrawing) return; isDrawing = false; const c = canvasRef.value; if (c) { signatureData.value = c.toDataURL('image/png'); form.setFieldValue('signatureData', signatureData.value) } }
function clearCanvas(): void { const ctx = getCtx(); const c = canvasRef.value; if (ctx && c) { ctx.clearRect(0, 0, c.width, c.height); signatureData.value = ''; form.setFieldValue('signatureData', '') } }
async function handleSubmit(): Promise<void> { const res = await form.submit(); result.value = res.errors.length > 0 ? '验证失败: ' + res.errors.map(e => e.message).join(', ') : JSON.stringify({ ...res.values, signatureData: signatureData.value ? '[Base64]' : '' }, null, 2) }
</script>

// playground-react/src/antd/field/SignaturePadForm.tsx
/**
 * 场景 34：手写签名板
 *
 * 覆盖：
 * - Canvas 签名板（可接入 signature_pad）
 * - 签名数据同步（Base64）
 * - 清空 / 撤销
 * - 三种模式切换
 */
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { observer } from 'mobx-react-lite';
import { FormProvider, FormField, useCreateForm } from '@moluoxixi/react';
import { setupAntd } from '@moluoxixi/ui-antd';
import { Button, Typography, Alert, Segmented, Form, Input, Space } from 'antd';
import { ClearOutlined } from '@ant-design/icons';
import type { FieldInstance } from '@moluoxixi/core';
import type { FieldPattern } from '@moluoxixi/shared';

const { Title, Paragraph, Text } = Typography;

setupAntd();

const MODE_OPTIONS = [
  { label: '编辑态', value: 'editable' },
  { label: '阅读态', value: 'readOnly' },
  { label: '禁用态', value: 'disabled' },
];

/** Canvas 签名板 */
const SignatureCanvas = ({
  value,
  onChange,
  disabled,
}: {
  value: string;
  onChange: (dataUrl: string) => void;
  disabled: boolean;
}): React.ReactElement => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const isDrawingRef = useRef(false);

  /** 获取绘图上下文 */
  const getCtx = (): CanvasRenderingContext2D | null => canvasRef.current?.getContext('2d') ?? null;

  /** 获取鼠标在 canvas 中的位置 */
  const getPos = (e: React.MouseEvent): { x: number; y: number } => {
    const rect = canvasRef.current!.getBoundingClientRect();
    return { x: e.clientX - rect.left, y: e.clientY - rect.top };
  };

  const handleMouseDown = (e: React.MouseEvent): void => {
    if (disabled) return;
    isDrawingRef.current = true;
    const ctx = getCtx();
    if (!ctx) return;
    const pos = getPos(e);
    ctx.beginPath();
    ctx.moveTo(pos.x, pos.y);
  };

  const handleMouseMove = (e: React.MouseEvent): void => {
    if (!isDrawingRef.current || disabled) return;
    const ctx = getCtx();
    if (!ctx) return;
    const pos = getPos(e);
    ctx.lineWidth = 2;
    ctx.lineCap = 'round';
    ctx.strokeStyle = '#333';
    ctx.lineTo(pos.x, pos.y);
    ctx.stroke();
  };

  const handleMouseUp = (): void => {
    if (!isDrawingRef.current) return;
    isDrawingRef.current = false;
    const canvas = canvasRef.current;
    if (canvas) onChange(canvas.toDataURL('image/png'));
  };

  /** 清空画布 */
  const clear = useCallback((): void => {
    const ctx = getCtx();
    const canvas = canvasRef.current;
    if (ctx && canvas) {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      onChange('');
    }
  }, [onChange]);

  /* 恢复已有签名 */
  useEffect(() => {
    if (!value) return;
    const ctx = getCtx();
    const canvas = canvasRef.current;
    if (!ctx || !canvas) return;
    const img = new Image();
    img.onload = () => { ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.drawImage(img, 0, 0); };
    img.src = value;
  }, []);

  return (
    <div>
      <canvas
        ref={canvasRef}
        width={500}
        height={200}
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        style={{
          border: '1px solid #d9d9d9',
          borderRadius: 8,
          cursor: disabled ? 'not-allowed' : 'crosshair',
          background: disabled ? '#f5f5f5' : '#fff',
          display: 'block',
        }}
      />
      {!disabled && (
        <Button icon={<ClearOutlined />} size="small" onClick={clear} style={{ marginTop: 8 }}>
          清空签名
        </Button>
      )}
    </div>
  );
};

export const SignaturePadForm = observer((): React.ReactElement => {
  const [mode, setMode] = useState<FieldPattern>('editable');
  const [result, setResult] = useState('');

  const form = useCreateForm({
    initialValues: { signerName: '', signatureData: '' },
  });

  useEffect(() => {
    form.createField({ name: 'signerName', label: '签名人', required: true });
    form.createField({ name: 'signatureData', label: '签名' });
  }, []);

  const switchMode = (p: FieldPattern): void => {
    setMode(p);
    ['signerName', 'signatureData'].forEach((n) => { const f = form.getField(n); if (f) f.pattern = p; });
  };

  const handleSubmit = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    const res = await form.submit();
    if (res.errors.length > 0) { setResult('验证失败: ' + res.errors.map((err) => err.message).join(', ')); }
    else {
      const data = { ...res.values, signatureData: (res.values as Record<string, unknown>).signatureData ? '[Base64 Image Data]' : '' };
      setResult(JSON.stringify(data, null, 2));
    }
  };

  return (
    <div>
      <Title level={3}>手写签名板</Title>
      <Paragraph type="secondary">Canvas 手写签名 / Base64 数据同步 / 清空操作 / 三种模式</Paragraph>
      <Segmented value={mode} onChange={(v) => switchMode(v as FieldPattern)} options={MODE_OPTIONS} style={{ marginBottom: 16 }} />

      <FormProvider form={form}>
        <form onSubmit={handleSubmit} noValidate>
          <FormField name="signerName">
            {(field: FieldInstance) => (
              <Form.Item label={field.label} required={field.required}>
                <Input value={(field.value as string) ?? ''} onChange={(e) => field.setValue(e.target.value)} disabled={mode === 'disabled'} readOnly={mode === 'readOnly'} style={{ width: 300 }} />
              </Form.Item>
            )}
          </FormField>
          <FormField name="signatureData">
            {(field: FieldInstance) => (
              <Form.Item label="手写签名">
                {mode === 'readOnly' || mode === 'preview' ? (
                  (field.value as string) ? (
                    <img src={field.value as string} alt="签名" style={{ border: '1px solid #d9d9d9', borderRadius: 8, maxWidth: 500 }} />
                  ) : (
                    <Text type="secondary">暂无签名</Text>
                  )
                ) : (
                  <SignatureCanvas
                    value={(field.value as string) ?? ''}
                    onChange={(v) => field.setValue(v)}
                    disabled={mode === 'disabled'}
                  />
                )}
              </Form.Item>
            )}
          </FormField>
          {mode === 'editable' && (<Space><Button type="primary" htmlType="submit">提交</Button><Button onClick={() => form.reset()}>重置</Button></Space>)}
        </form>
      </FormProvider>

      {result && (<Alert style={{ marginTop: 16 }} type={result.startsWith('验证失败') ? 'error' : 'success'} message="提交结果" description={<pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{result}</pre>} />)}
    </div>
  );
});
